import {
  CommandCenterThread,
  CommandCenterMessage,
  DigestStats,
  GuestPreferences,
  ActivityEvent,
} from './types';

export const digestStats: DigestStats = {
  serviceRecovery: 3,
  aiHandledOvernight: 12,
  escalationsPending: 2,
  avgResponseTime: '1m 23s',
};

export const mockCommandCenterThreads: CommandCenterThread[] = [
  // === NEEDS RESPONSE (5) ===
  {
    id: 'cc-1',
    guestId: 'guest-emily',
    reservationId: 'res-emily-jul',
    channel: 'SMS',
    priority: 'urgent',
    aiStatus: 'needs_response',
    sentiment: 'negative',
    lastMessage: 'I\'ve been waiting 30 minutes for the extra pillows I requested. This is unacceptable for a Diamond member.',
    lastMessageAt: new Date('2026-03-16T10:02:00'),
    isUnread: true,
    aiSummary: 'Diamond Elite guest upset about delayed pillow delivery. Has been waiting 30 min. High-value guest — 12 stays this year.',
    suggestedActions: [
      { type: 'create_ticket', label: 'Create service ticket', description: 'Housekeeping — deliver extra pillows to Rm 1204' },
      { type: 'send_draft', label: 'Send apology', description: 'Apologize for the delay and confirm pillows are on the way' },
    ],
    isCompleted: false,
  },
  {
    id: 'cc-2',
    guestId: 'guest-marco',
    reservationId: 'res-marco-nov',
    channel: 'WhatsApp',
    priority: 'high',
    aiStatus: 'needs_response',
    sentiment: 'neutral',
    lastMessage: 'Hi, I need to extend my stay by two nights if possible. Can someone check availability?',
    lastMessageAt: new Date('2026-03-16T09:58:00'),
    isUnread: true,
    aiSummary: 'Guest requesting 2-night extension. Currently in Rm 802 (King Suite). Checkout was Mar 18, wants to extend to Mar 20.',
    suggestedActions: [
      { type: 'send_draft', label: 'Check availability', description: 'Confirm room availability for Mar 18-20 extension' },
    ],
    isCompleted: false,
  },
  {
    id: 'cc-3',
    guestId: 'guest-sarah',
    reservationId: 'res-sarah-jul',
    channel: 'Email',
    priority: 'normal',
    aiStatus: 'needs_response',
    sentiment: 'neutral',
    lastMessage: 'Could you send me an itemized receipt for my stay? I need it for my expense report by end of day.',
    lastMessageAt: new Date('2026-03-16T09:45:00'),
    isUnread: true,
    aiSummary: 'Platinum Elite guest requesting itemized receipt for expense report. Time-sensitive — needs it today.',
    suggestedActions: [
      { type: 'send_draft', label: 'Send receipt', description: 'Generate and send itemized folio to guest email' },
    ],
    isCompleted: false,
  },
  {
    id: 'cc-4',
    guestId: 'guest-robert',
    reservationId: 'res-robert-jul',
    channel: 'SMS',
    priority: 'high',
    aiStatus: 'needs_response',
    sentiment: 'negative',
    lastMessage: 'The room next door has been extremely loud since midnight. I haven\'t slept at all. I need this resolved immediately.',
    lastMessageAt: new Date('2026-03-16T09:30:00'),
    isUnread: true,
    aiSummary: 'Diamond Elite guest — noise complaint about adjacent room. Has not slept. Needs immediate resolution. Consider room move or comp.',
    suggestedActions: [
      { type: 'create_ticket', label: 'Create noise complaint', description: 'Security — noise complaint Rm 1508, adjacent room' },
      { type: 'offer_upgrade', label: 'Offer room move', description: 'Move guest to available quiet room on higher floor' },
    ],
    isCompleted: false,
  },
  {
    id: 'cc-5',
    guestId: 'guest-maria',
    reservationId: 'res-maria-jul',
    channel: 'WhatsApp',
    priority: 'normal',
    aiStatus: 'needs_response',
    sentiment: 'positive',
    lastMessage: '¡Hola! ¿Podrían reservarme una mesa para 4 personas en el restaurante del hotel para esta noche a las 8pm?',
    lastMessageAt: new Date('2026-03-16T09:15:00'),
    isUnread: true,
    aiSummary: 'Guest requesting dinner reservation for 4 at hotel restaurant tonight at 8pm. Message in Spanish — guest prefers Spanish.',
    suggestedActions: [
      { type: 'send_draft', label: 'Confirm reservation', description: 'Book table for 4 at 8pm and confirm in Spanish' },
    ],
    isCompleted: false,
  },

  // === NEEDS ATTENTION (3) ===
  {
    id: 'cc-6',
    guestId: 'guest-liam',
    reservationId: 'res-liam-nov',
    channel: 'Expedia',
    priority: 'high',
    aiStatus: 'needs_attention',
    sentiment: 'angry',
    lastMessage: 'This hotel charged me twice for the room. I want a refund immediately or I\'m leaving a 1-star review.',
    lastMessageAt: new Date('2026-03-16T09:10:00'),
    isUnread: true,
    aiSummary: 'OTA guest threatening negative review over double charge. AI responded with acknowledgment but needs human to verify billing and process refund.',
    suggestedActions: [
      { type: 'create_ticket', label: 'Billing investigation', description: 'Front desk — verify double charge on Rm 605 folio' },
    ],
    isCompleted: false,
  },
  {
    id: 'cc-7',
    guestId: 'guest-olivia',
    reservationId: 'res-olivia-jul',
    channel: 'SMS',
    priority: 'normal',
    aiStatus: 'needs_attention',
    sentiment: 'negative',
    lastMessage: 'The AI told me late checkout was available until 2pm but the front desk said no. Which is it?',
    lastMessageAt: new Date('2026-03-16T08:55:00'),
    isUnread: false,
    aiSummary: 'Platinum Elite guest got conflicting info — AI offered 2pm late checkout, front desk denied it. AI/staff alignment issue. Guest is frustrated.',
    suggestedActions: [
      { type: 'send_draft', label: 'Resolve conflict', description: 'Apologize for confusion and honor the 2pm late checkout' },
    ],
    isCompleted: false,
  },
  {
    id: 'cc-8',
    guestId: 'guest-james',
    reservationId: 'res-james-jul',
    channel: 'Booking.com',
    priority: 'normal',
    aiStatus: 'needs_attention',
    sentiment: 'neutral',
    lastMessage: 'Is there a shuttle service to JFK airport? I need to catch a 6am flight.',
    lastMessageAt: new Date('2026-03-16T08:40:00'),
    isUnread: false,
    aiSummary: 'OTA guest asking about airport shuttle to JFK for early morning flight. AI provided general info but hotel doesn\'t have a shuttle — needs human to suggest alternatives.',
    suggestedActions: [
      { type: 'send_draft', label: 'Suggest car service', description: 'Recommend hotel\'s partner car service for early JFK transfer' },
    ],
    isCompleted: false,
  },

  // === AI HANDLED (12) ===
  {
    id: 'cc-9',
    guestId: 'guest-brooklyn',
    reservationId: 'res-brooklyn-nov',
    channel: 'SMS',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'positive',
    lastMessage: 'Got it, thanks!',
    lastMessageAt: new Date('2026-03-16T08:30:00'),
    isUnread: false,
    aiSummary: 'Guest asked about pool hours. AI responded: 6am-10pm daily. Guest confirmed.',
    isCompleted: false,
  },
  {
    id: 'cc-10',
    guestId: 'guest-kristin',
    reservationId: 'res-kristin-nov',
    channel: 'WhatsApp',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'positive',
    lastMessage: 'Great, that\'s super helpful. Thank you!',
    lastMessageAt: new Date('2026-03-16T08:20:00'),
    isUnread: false,
    aiSummary: 'Guest asked for restaurant recommendations near Central Park. AI provided 5 options with cuisine types and distance.',
    isCompleted: false,
  },
  {
    id: 'cc-11',
    guestId: 'guest-noah',
    reservationId: 'res-noah-jul',
    channel: 'SMS',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'neutral',
    lastMessage: 'Perfect, I\'ll be down in 10 minutes.',
    lastMessageAt: new Date('2026-03-16T08:10:00'),
    isUnread: false,
    aiSummary: 'Guest confirmed check-out time. AI reminded about express checkout option.',
    isCompleted: false,
  },
  {
    id: 'cc-12',
    guestId: 'guest-emma',
    reservationId: 'res-emma-jul',
    channel: 'Email',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'positive',
    lastMessage: 'Thanks for the info about the gym hours. I\'ll head down now.',
    lastMessageAt: new Date('2026-03-16T07:55:00'),
    isUnread: false,
    aiSummary: 'Guest asked about gym hours and equipment. AI responded: 24/7 access, full equipment list provided.',
    isCompleted: false,
  },
  {
    id: 'cc-13',
    guestId: 'guest-gel',
    reservationId: 'res-gel-mar',
    channel: 'SMS',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'neutral',
    lastMessage: 'OK sounds good.',
    lastMessageAt: new Date('2026-03-16T07:45:00'),
    isUnread: false,
    aiSummary: 'Guest asked about WiFi password. AI provided network name and password.',
    isCompleted: false,
  },
  {
    id: 'cc-14',
    guestId: 'guest-jack',
    reservationId: 'res-jack-mar',
    channel: 'WhatsApp',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'positive',
    lastMessage: 'Awesome, that really clears things up. Thanks!',
    lastMessageAt: new Date('2026-03-16T07:30:00'),
    isUnread: false,
    aiSummary: 'Guest asked about parking options. AI provided valet ($65/night) and self-park ($45/night) details.',
    isCompleted: false,
  },
  {
    id: 'cc-15',
    guestId: 'guest-nook',
    reservationId: 'res-nook-mar',
    channel: 'SMS',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'neutral',
    lastMessage: 'Thank you for the wake-up call confirmation.',
    lastMessageAt: new Date('2026-03-16T07:15:00'),
    isUnread: false,
    aiSummary: 'Guest requested 6am wake-up call. AI confirmed and set reminder.',
    isCompleted: false,
  },
  {
    id: 'cc-16',
    guestId: 'guest-diana',
    reservationId: 'res-diana-mar',
    channel: 'WhatsApp',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'positive',
    lastMessage: '¡Perfecto! Gracias por la información.',
    lastMessageAt: new Date('2026-03-16T07:00:00'),
    isUnread: false,
    aiSummary: 'Spanish-speaking guest asked about spa services. AI responded in Spanish with spa menu and availability.',
    isCompleted: false,
  },
  {
    id: 'cc-17',
    guestId: 'guest-chen',
    reservationId: 'res-chen-mar',
    channel: 'Web',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'neutral',
    lastMessage: 'I see. I\'ll check the business center then.',
    lastMessageAt: new Date('2026-03-16T06:45:00'),
    isUnread: false,
    aiSummary: 'Guest asked about printing services. AI directed to business center on 2nd floor, open 24/7.',
    isCompleted: false,
  },
  {
    id: 'cc-18',
    guestId: 'guest-miguel',
    reservationId: 'res-miguel-nov',
    channel: 'SMS',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'positive',
    lastMessage: 'Can I have extra face towels to the room please?',
    lastMessageAt: new Date('2026-03-16T06:30:00'),
    isUnread: false,
    aiSummary: 'Guest requested extra towels. AI created service ticket and confirmed delivery within 15 minutes.',
    suggestedActions: [
      { type: 'create_ticket', label: 'Verify delivery', description: 'Check if towels were delivered to Rm 910' },
    ],
    isCompleted: false,
  },
  {
    id: 'cc-19',
    guestId: 'guest-john-s',
    reservationId: 'res-john-jul',
    channel: 'SMS',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'positive',
    lastMessage: 'Those restaurant suggestions look great, thanks!',
    lastMessageAt: new Date('2026-03-16T06:15:00'),
    isUnread: false,
    aiSummary: 'Guest asked for nearby restaurant recommendations. AI provided 5 options with ratings and distance.',
    isCompleted: false,
  },
  {
    id: 'cc-20',
    guestId: 'guest-emerson-s',
    reservationId: 'res-emerson-jun',
    channel: 'Email',
    priority: 'low',
    aiStatus: 'ai_handled',
    sentiment: 'neutral',
    lastMessage: 'Thanks for confirming my reservation details.',
    lastMessageAt: new Date('2026-03-16T06:00:00'),
    isUnread: false,
    aiSummary: 'Gold Elite guest confirming upcoming reservation details. AI provided full itinerary summary.',
    isCompleted: false,
  },
];

export const mockCommandCenterMessages: Record<string, CommandCenterMessage[]> = {
  'cc-1': [
    { id: 'cc-m-1-1', threadId: 'cc-1', sender: 'system', content: 'Emily Smith checked in to Rm 1204 — Diamond Elite', timestamp: new Date('2026-03-15T15:00:00') },
    { id: 'cc-m-1-2', threadId: 'cc-1', sender: 'guest', content: 'Hi, could I get some extra pillows for my room please?', timestamp: new Date('2026-03-16T09:30:00'), channel: 'SMS' },
    { id: 'cc-m-1-3', threadId: 'cc-1', sender: 'ai', content: 'Of course! I\'ll have housekeeping bring extra pillows to Room 1204 right away. Is there anything else I can help with?', timestamp: new Date('2026-03-16T09:31:00'), channel: 'SMS' },
    { id: 'cc-m-1-4', threadId: 'cc-1', sender: 'guest', content: 'That was 30 minutes ago and nobody has come.', timestamp: new Date('2026-03-16T10:00:00'), channel: 'SMS' },
    { id: 'cc-m-1-5', threadId: 'cc-1', sender: 'guest', content: 'I\'ve been waiting 30 minutes for the extra pillows I requested. This is unacceptable for a Diamond member.', timestamp: new Date('2026-03-16T10:02:00'), channel: 'SMS' },
  ],
  'cc-2': [
    { id: 'cc-m-2-1', threadId: 'cc-2', sender: 'guest', content: 'Hi, I need to extend my stay by two nights if possible. Can someone check availability?', timestamp: new Date('2026-03-16T09:58:00'), channel: 'WhatsApp' },
  ],
  'cc-3': [
    { id: 'cc-m-3-1', threadId: 'cc-3', sender: 'guest', content: 'Could you send me an itemized receipt for my stay? I need it for my expense report by end of day.', timestamp: new Date('2026-03-16T09:45:00'), channel: 'Email' },
  ],
  'cc-4': [
    { id: 'cc-m-4-1', threadId: 'cc-4', sender: 'guest', content: 'The room next door has been loud since midnight. I can\'t sleep.', timestamp: new Date('2026-03-16T06:00:00'), channel: 'SMS' },
    { id: 'cc-m-4-2', threadId: 'cc-4', sender: 'ai', content: 'I\'m sorry to hear about the noise disturbance. I\'ve alerted our security team and they\'ll address the situation right away. We sincerely apologize for the inconvenience.', timestamp: new Date('2026-03-16T06:01:00'), channel: 'SMS' },
    { id: 'cc-m-4-3', threadId: 'cc-4', sender: 'guest', content: 'It\'s now 9:30am and it happened AGAIN last night. I haven\'t slept at all. I need this resolved immediately.', timestamp: new Date('2026-03-16T09:30:00'), channel: 'SMS' },
  ],
  'cc-5': [
    { id: 'cc-m-5-1', threadId: 'cc-5', sender: 'guest', content: '¡Hola! ¿Podrían reservarme una mesa para 4 personas en el restaurante del hotel para esta noche a las 8pm?', timestamp: new Date('2026-03-16T09:15:00'), channel: 'WhatsApp' },
  ],
  'cc-6': [
    { id: 'cc-m-6-1', threadId: 'cc-6', sender: 'guest', content: 'I just checked my credit card and I was charged twice for my room. What is going on?', timestamp: new Date('2026-03-16T08:50:00'), channel: 'Expedia' },
    { id: 'cc-m-6-2', threadId: 'cc-6', sender: 'ai', content: 'I\'m sorry to hear about the duplicate charge. I\'ve flagged this for our billing team to review immediately. We\'ll get this resolved as quickly as possible.', timestamp: new Date('2026-03-16T08:51:00'), channel: 'Expedia' },
    { id: 'cc-m-6-3', threadId: 'cc-6', sender: 'guest', content: 'This hotel charged me twice for the room. I want a refund immediately or I\'m leaving a 1-star review.', timestamp: new Date('2026-03-16T09:10:00'), channel: 'Expedia' },
  ],
  'cc-7': [
    { id: 'cc-m-7-1', threadId: 'cc-7', sender: 'guest', content: 'Can I get a late checkout? Maybe until 2pm?', timestamp: new Date('2026-03-16T08:30:00'), channel: 'SMS' },
    { id: 'cc-m-7-2', threadId: 'cc-7', sender: 'ai', content: 'Absolutely! As a Platinum Elite member, late checkout until 2pm is available for your stay. I\'ve updated your checkout time.', timestamp: new Date('2026-03-16T08:31:00'), channel: 'SMS' },
    { id: 'cc-m-7-3', threadId: 'cc-7', sender: 'guest', content: 'The AI told me late checkout was available until 2pm but the front desk said no. Which is it?', timestamp: new Date('2026-03-16T08:55:00'), channel: 'SMS' },
  ],
  'cc-8': [
    { id: 'cc-m-8-1', threadId: 'cc-8', sender: 'guest', content: 'Is there a shuttle service to JFK airport? I need to catch a 6am flight.', timestamp: new Date('2026-03-16T08:40:00'), channel: 'Booking.com' },
    { id: 'cc-m-8-2', threadId: 'cc-8', sender: 'ai', content: 'For early morning flights from JFK, I\'d recommend arranging transportation in advance. The hotel can help coordinate a car service. Would you like me to look into options?', timestamp: new Date('2026-03-16T08:41:00'), channel: 'Booking.com' },
  ],
};

export const guestPreferences: Record<string, GuestPreferences> = {
  'guest-emily': {
    coffeePreference: 'Medium roast, black',
    pillow: 'Extra firm',
    roomTemp: '68°F',
    notes: ['Prefers high floor', 'Regular guest — 12 stays this year', 'Allergic to feather pillows'],
  },
  'guest-robert': {
    coffeePreference: 'Espresso, double shot',
    pillow: 'Memory foam',
    roomTemp: '70°F',
    notes: ['Business traveler', 'Needs quiet room for calls', 'Prefers corner rooms'],
  },
  'guest-olivia': {
    pillow: 'Soft down',
    dietaryRestrictions: 'Vegetarian',
    notes: ['Anniversary trip', 'Requested champagne on arrival'],
  },
  'guest-marco': {
    coffeePreference: 'Cappuccino',
    notes: ['Extended stay guest', 'Works remotely — needs strong WiFi'],
  },
  'guest-sarah': {
    dietaryRestrictions: 'Gluten-free',
    notes: ['Corporate account — needs receipts formatted for Deloitte'],
  },
};

export const activityEvents: Record<string, ActivityEvent[]> = {
  'guest-emily': [
    { id: 'ae-1', type: 'check_in', description: 'Checked in to Rm 1204', timestamp: new Date('2026-03-15T15:00:00') },
    { id: 'ae-2', type: 'upsell', description: 'Accepted late checkout (2pm)', timestamp: new Date('2026-03-15T15:05:00') },
    { id: 'ae-3', type: 'ai_response', description: 'AI responded to restaurant recommendation request', timestamp: new Date('2026-03-15T18:30:00') },
    { id: 'ae-4', type: 'message', description: 'Requested extra pillows via SMS', timestamp: new Date('2026-03-16T09:30:00') },
    { id: 'ae-5', type: 'sentiment_flag', description: 'Negative sentiment detected — service delay complaint', timestamp: new Date('2026-03-16T10:02:00') },
  ],
  'guest-robert': [
    { id: 'ae-6', type: 'check_in', description: 'Checked in to Rm 1508', timestamp: new Date('2026-03-15T14:00:00') },
    { id: 'ae-7', type: 'message', description: 'Noise complaint — adjacent room', timestamp: new Date('2026-03-16T06:00:00') },
    { id: 'ae-8', type: 'ai_response', description: 'AI acknowledged noise complaint, alerted security', timestamp: new Date('2026-03-16T06:01:00') },
    { id: 'ae-9', type: 'sentiment_flag', description: 'Escalation — recurring noise issue, guest has not slept', timestamp: new Date('2026-03-16T09:30:00') },
  ],
  'guest-liam': [
    { id: 'ae-10', type: 'check_in', description: 'Checked in to Rm 605 via Expedia', timestamp: new Date('2026-03-14T16:00:00') },
    { id: 'ae-11', type: 'message', description: 'Reported double charge via Expedia messaging', timestamp: new Date('2026-03-16T08:50:00') },
    { id: 'ae-12', type: 'sentiment_flag', description: 'Angry sentiment — threatening 1-star review', timestamp: new Date('2026-03-16T09:10:00') },
  ],
};
