/**
 * Messaging Mock Data
 *
 * Thread and message data that references canonical guests and reservations.
 */

import { Thread, Message } from './types';

/**
 * Mock threads - link to canonical guest and reservation IDs
 */
export const mockThreads: Thread[] = [
  {
    id: '1',
    guestId: 'guest-emily',
    reservationId: 'res-emily-jul',
    lastMessage: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '2',
    guestId: 'guest-miguel',
    reservationId: 'res-miguel-nov',
    lastMessage: 'Can I have extra face towels to the room please?',
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '3',
    guestId: 'guest-brooklyn',
    reservationId: 'res-brooklyn-nov',
    lastMessage: 'Got it, thanks.',
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '4',
    guestId: 'guest-marco',
    reservationId: 'res-marco-nov',
    lastMessage: 'What time will the pool close?',
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '5',
    guestId: 'guest-kristin',
    reservationId: 'res-kristin-nov',
    lastMessage: "Great. That's super helpful.",
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '6',
    guestId: 'guest-liam',
    reservationId: 'res-liam-nov',
    lastMessage: 'Awesome! That really clears things up.',
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '7',
    guestId: 'guest-olivia',
    reservationId: 'res-olivia-nov',
    lastMessage: 'Fantastic! This is exactly what I needed.',
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '8',
    guestId: 'guest-noah',
    reservationId: 'res-noah-nov',
    lastMessage: 'Perfect! This information is incredibly useful.',
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '9',
    guestId: 'guest-emma',
    reservationId: 'res-emma-nov',
    lastMessage: 'Excellent! I appreciate your help with this.',
    lastMessageAt: new Date('2024-11-19T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  // Archived conversations
  {
    id: '10',
    guestId: 'guest-sarah',
    reservationId: 'res-sarah-nov',
    lastMessage: 'Thank you so much for the wonderful stay! Everything was perfect.',
    lastMessageAt: new Date('2024-11-15T11:30:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '11',
    guestId: 'guest-james',
    reservationId: 'res-james-nov',
    lastMessage: 'All set, thanks for resolving the WiFi issue.',
    lastMessageAt: new Date('2024-11-14T16:45:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '12',
    guestId: 'guest-maria',
    reservationId: 'res-maria-nov',
    lastMessage: 'Perfect, the late checkout worked out great. See you next time!',
    lastMessageAt: new Date('2024-11-13T14:20:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '13',
    guestId: 'guest-robert',
    reservationId: 'res-robert-nov',
    lastMessage: 'Appreciate all your help with the room upgrade and restaurant reservations!',
    lastMessageAt: new Date('2024-11-12T10:15:00'),
    isUnread: false,
    status: 'archived',
  },
];

/**
 * Mock messages - organized by thread ID
 */
export const mockMessages: Record<string, Message[]> = {
  // Emily Smith's conversation
  '1': [
    {
      id: 'm1',
      threadId: '1',
      sender: 'guest',
      content: 'I will arrive late today. My flight is delayed.',
      timestamp: new Date('2024-11-19T17:10:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2',
      threadId: '1',
      sender: 'ai',
      content: 'Thanks for letting us know!',
      timestamp: new Date('2024-11-19T17:25:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm3',
      threadId: '1',
      sender: 'guest',
      content: 'Give me a list of nearby restaurants',
      timestamp: new Date('2024-11-19T18:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm4',
      threadId: '1',
      sender: 'ai',
      content: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
      timestamp: new Date('2024-11-19T18:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Miguel's conversation
  '2': [
    {
      id: 'm5',
      threadId: '2',
      sender: 'guest',
      content: 'Can I have extra face towels to the room please?',
      timestamp: new Date('2024-11-19T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Brooklyn's conversation
  '3': [
    {
      id: 'm6',
      threadId: '3',
      sender: 'guest',
      content: 'What are the check-out procedures?',
      timestamp: new Date('2024-11-19T09:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm7',
      threadId: '3',
      sender: 'ai',
      content: 'Check-out time is 11:00 AM. You can check out at the front desk or use express check-out through the TV in your room.',
      timestamp: new Date('2024-11-19T09:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm8',
      threadId: '3',
      sender: 'guest',
      content: 'Got it, thanks.',
      timestamp: new Date('2024-11-19T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Marco's conversation
  '4': [
    {
      id: 'm9',
      threadId: '4',
      sender: 'guest',
      content: 'What time will the pool close?',
      timestamp: new Date('2024-11-19T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Kristin's conversation
  '5': [
    {
      id: 'm10',
      threadId: '5',
      sender: 'guest',
      content: 'Is there a gym in the hotel?',
      timestamp: new Date('2024-11-19T09:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm11',
      threadId: '5',
      sender: 'ai',
      content: 'Yes! Our fitness center is on the 2nd floor and is open 24/7 for all guests.',
      timestamp: new Date('2024-11-19T09:46:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm12',
      threadId: '5',
      sender: 'guest',
      content: "Great. That's super helpful.",
      timestamp: new Date('2024-11-19T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Liam's conversation
  '6': [
    {
      id: 'm13',
      threadId: '6',
      sender: 'guest',
      content: 'Can you explain the parking options?',
      timestamp: new Date('2024-11-19T09:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm14',
      threadId: '6',
      sender: 'ai',
      content: 'We offer valet parking for $35/day and self-parking for $25/day. Both are available 24/7.',
      timestamp: new Date('2024-11-19T09:22:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm15',
      threadId: '6',
      sender: 'guest',
      content: 'Awesome! That really clears things up.',
      timestamp: new Date('2024-11-19T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Olivia's conversation
  '7': [
    {
      id: 'm16',
      threadId: '7',
      sender: 'guest',
      content: 'What time is breakfast served?',
      timestamp: new Date('2024-11-19T09:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm17',
      threadId: '7',
      sender: 'ai',
      content: 'Our complimentary breakfast buffet is served daily from 6:30 AM to 10:30 AM in the main dining room.',
      timestamp: new Date('2024-11-19T09:02:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm18',
      threadId: '7',
      sender: 'guest',
      content: 'Fantastic! This is exactly what I needed.',
      timestamp: new Date('2024-11-19T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Noah's conversation
  '8': [
    {
      id: 'm19',
      threadId: '8',
      sender: 'guest',
      content: 'Do you have any recommendations for local attractions?',
      timestamp: new Date('2024-11-19T08:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm20',
      threadId: '8',
      sender: 'ai',
      content: "Absolutely! Within walking distance you have the waterfront, several museums, and historic downtown. I can also arrange tours if you're interested.",
      timestamp: new Date('2024-11-19T08:47:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm21',
      threadId: '8',
      sender: 'guest',
      content: 'Perfect! This information is incredibly useful.',
      timestamp: new Date('2024-11-19T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Emma's conversation
  '9': [
    {
      id: 'm22',
      threadId: '9',
      sender: 'guest',
      content: 'Can I request a late checkout?',
      timestamp: new Date('2024-11-19T08:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm23',
      threadId: '9',
      sender: 'ai',
      content: 'Yes, we can accommodate a late checkout until 2:00 PM for an additional $50, subject to availability. Would you like me to arrange that for you?',
      timestamp: new Date('2024-11-19T08:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm24',
      threadId: '9',
      sender: 'guest',
      content: 'Excellent! I appreciate your help with this.',
      timestamp: new Date('2024-11-19T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Sarah Martinez - Archived
  '10': [
    {
      id: 'm25',
      threadId: '10',
      sender: 'guest',
      content: 'Hi! Just checked in. The room looks lovely!',
      timestamp: new Date('2024-11-12T15:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm26',
      threadId: '10',
      sender: 'staff',
      content: 'Welcome Sarah! So glad you like it. Please let us know if you need anything during your stay.',
      timestamp: new Date('2024-11-12T15:22:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm27',
      threadId: '10',
      sender: 'guest',
      content: 'Thank you so much for the wonderful stay! Everything was perfect.',
      timestamp: new Date('2024-11-15T11:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // James Chen - Archived
  '11': [
    {
      id: 'm35',
      threadId: '11',
      sender: 'guest',
      content: "The WiFi in my room isn't working. I need to join a video call in 30 minutes.",
      timestamp: new Date('2024-11-13T14:15:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm36',
      threadId: '11',
      sender: 'staff',
      content: "I'm so sorry about that! Let me get our IT team to your room right away.",
      timestamp: new Date('2024-11-13T14:16:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm42',
      threadId: '11',
      sender: 'guest',
      content: 'All set, thanks for resolving the WiFi issue.',
      timestamp: new Date('2024-11-14T16:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Maria Garcia - Archived
  '12': [
    {
      id: 'm43',
      threadId: '12',
      sender: 'guest',
      content: "Hola! Is it possible to have a late checkout? My flight isn't until 6pm.",
      timestamp: new Date('2024-11-12T09:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm44',
      threadId: '12',
      sender: 'ai',
      content: 'Hi Maria! Yes, we can arrange a late checkout for you. Would 3:00 PM work for your schedule?',
      timestamp: new Date('2024-11-12T09:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm50',
      threadId: '12',
      sender: 'guest',
      content: 'Perfect, the late checkout worked out great. See you next time!',
      timestamp: new Date('2024-11-13T14:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Robert Thompson - Archived
  '13': [
    {
      id: 'm51',
      threadId: '13',
      sender: 'guest',
      content: "I'd like to request a room upgrade if possible. Staying for 4 nights.",
      timestamp: new Date('2024-11-08T16:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm52',
      threadId: '13',
      sender: 'staff',
      content: "Good evening Mr. Thompson! As a Diamond Elite member, we'd be happy to upgrade you to a junior suite at no additional charge.",
      timestamp: new Date('2024-11-08T16:05:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm61',
      threadId: '13',
      sender: 'guest',
      content: 'Appreciate all your help with the room upgrade and restaurant reservations!',
      timestamp: new Date('2024-11-12T10:15:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
};
