/**
 * Messaging Mock Data
 *
 * Thread and message data that references canonical guests and reservations.
 */

import { Thread, Message, EmailThread } from './types';

/**
 * Mock threads - link to canonical guest and reservation IDs
 */
export const mockThreads: Thread[] = [
  // Multi-reservation thread (1 auto-linked + 3 manually linked)
  {
    id: '14',
    contactNumber: '+16507665555',
    linkedReservationIds: ['res-john-jul', 'res-james-jul', 'res-ethan-jul', 'res-liam-aug'],
    lastMessage: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: true,
    status: 'inbox',
  },
  // Single manually-linked reservation (phone doesn't match)
  {
    id: '15',
    contactNumber: '+13305559999',
    linkedReservationIds: ['res-emerson-jun'],
    lastMessage: 'Hi, I wanted to confirm my reservation for next month.',
    lastMessageAt: new Date('2026-03-16T09:50:00'),
    isUnread: true,
    status: 'inbox',
  },
  // Empty thread (no linked reservations)
  {
    id: '16',
    contactNumber: '+12125550000',
    linkedReservationIds: [],
    lastMessage: 'Is there availability for this weekend?',
    lastMessageAt: new Date('2026-03-16T09:30:00'),
    isUnread: false,
    status: 'inbox',
  },
  // Single auto-linked threads (existing guests — phone matches contactNumber)
  {
    id: '1',
    contactNumber: '+15005550012',
    linkedReservationIds: ['res-emily-jul'],
    lastMessage: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '2',
    contactNumber: '+15005550013',
    linkedReservationIds: ['res-miguel-nov'],
    lastMessage: 'Can I have extra face towels to the room please?',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '3',
    contactNumber: '+15005550014',
    linkedReservationIds: ['res-brooklyn-nov'],
    lastMessage: 'Got it, thanks.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '4',
    contactNumber: '+15005550015',
    linkedReservationIds: ['res-marco-nov'],
    lastMessage: 'What time will the pool close?',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '5',
    contactNumber: '+15005550016',
    linkedReservationIds: ['res-kristin-nov'],
    lastMessage: "Great. That's super helpful.",
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '6',
    contactNumber: '+15005550017',
    linkedReservationIds: ['res-liam-nov'],
    lastMessage: 'Awesome! That really clears things up.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '7',
    contactNumber: '+15005550018',
    linkedReservationIds: ['res-olivia-nov'],
    lastMessage: 'Fantastic! This is exactly what I needed.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '8',
    contactNumber: '+15005550019',
    linkedReservationIds: ['res-noah-nov'],
    lastMessage: 'Perfect! This information is incredibly useful.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '9',
    contactNumber: '+15005550024',
    linkedReservationIds: ['res-emma-nov'],
    lastMessage: 'Excellent! I appreciate your help with this.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  // New guest threads
  {
    id: '17',
    contactNumber: '+15005550040',
    linkedReservationIds: ['res-priya-nov'],
    lastMessage: 'Could you arrange a taxi to the airport for tomorrow at 6 AM?',
    lastMessageAt: new Date('2026-03-16T09:15:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '18',
    contactNumber: '+15005550042',
    linkedReservationIds: ['res-yuki-nov'],
    lastMessage: 'Is there a Japanese restaurant nearby you would recommend?',
    lastMessageAt: new Date('2026-03-16T08:50:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '19',
    contactNumber: '+15005550043',
    linkedReservationIds: ['res-fatima-nov'],
    lastMessage: 'Thank you for the upgrade, the suite is beautiful!',
    lastMessageAt: new Date('2026-03-16T10:00:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '20',
    contactNumber: '+15005550045',
    linkedReservationIds: ['res-lucia-nov'],
    lastMessage: 'Can someone bring extra blankets to room 226?',
    lastMessageAt: new Date('2026-03-16T07:30:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '21',
    contactNumber: '+15005550050',
    linkedReservationIds: ['res-hiroshi-nov'],
    lastMessage: 'The room service menu — is it available after midnight?',
    lastMessageAt: new Date('2026-03-15T23:45:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '22',
    contactNumber: '+15005550057',
    linkedReservationIds: ['res-ingrid-nov'],
    lastMessage: 'Perfect, I will pick up the key at the front desk.',
    lastMessageAt: new Date('2026-03-15T16:20:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '23',
    contactNumber: '+15005550063',
    linkedReservationIds: ['res-thomas-k-nov'],
    lastMessage: 'Do you have a business center or somewhere I can print documents?',
    lastMessageAt: new Date('2026-03-16T08:00:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '24',
    contactNumber: '+15005550064',
    linkedReservationIds: ['res-rachel-nov'],
    lastMessage: 'Thank you, that was very helpful!',
    lastMessageAt: new Date('2026-03-15T15:30:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '25',
    contactNumber: '+15005550066',
    linkedReservationIds: ['res-chloe-nov'],
    lastMessage: 'Is the spa open on Sundays?',
    lastMessageAt: new Date('2026-03-16T09:00:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '26',
    contactNumber: '+15005550067',
    linkedReservationIds: ['res-andre-nov'],
    lastMessage: 'All good now, the AC is working fine.',
    lastMessageAt: new Date('2026-03-15T22:10:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '27',
    contactNumber: '+15005550068',
    linkedReservationIds: ['res-maya-nov'],
    lastMessage: 'We loved the complimentary breakfast. Thank you!',
    lastMessageAt: new Date('2026-03-16T10:30:00'),
    isUnread: false,
    status: 'inbox',
  },
  // Archived conversations
  {
    id: '10',
    contactNumber: '+15005550020',
    linkedReservationIds: ['res-sarah-nov'],
    lastMessage: 'Thank you so much for the wonderful stay! Everything was perfect.',
    lastMessageAt: new Date('2026-03-12T11:30:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '11',
    contactNumber: '+15005550021',
    linkedReservationIds: ['res-james-nov'],
    lastMessage: 'All set, thanks for resolving the WiFi issue.',
    lastMessageAt: new Date('2026-03-11T16:45:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '12',
    contactNumber: '+15005550022',
    linkedReservationIds: ['res-maria-nov'],
    lastMessage: 'Perfect, the late checkout worked out great. See you next time!',
    lastMessageAt: new Date('2026-03-10T14:20:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '13',
    contactNumber: '+15005550023',
    linkedReservationIds: ['res-robert-nov'],
    lastMessage: 'Appreciate all your help with the room upgrade and restaurant reservations!',
    lastMessageAt: new Date('2026-03-09T10:15:00'),
    isUnread: false,
    status: 'archived',
  },
];

/**
 * Mock messages - organized by thread ID
 */
export const mockMessages: Record<string, Message[]> = {
  // Multi-reservation thread — multi-channel (SMS + WhatsApp)
  '14': [
    {
      id: 'm100',
      threadId: '14',
      sender: 'guest',
      content: 'I will arrive late today. My flight is delayed.',
      timestamp: new Date('2026-03-16T17:10:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm101',
      threadId: '14',
      sender: 'ai',
      content: 'Thanks for letting us know!',
      timestamp: new Date('2026-03-16T17:25:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm102',
      threadId: '14',
      sender: 'guest',
      content: 'Give me a list of nearby restaurants',
      timestamp: new Date('2026-03-16T18:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm103',
      threadId: '14',
      sender: 'ai',
      content: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
      timestamp: new Date('2026-03-16T18:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // WhatsApp messages
    {
      id: 'm100-w1',
      threadId: '14',
      sender: 'guest',
      content: 'Hey, just following up — do you have any availability for a late checkout on the 18th?',
      timestamp: new Date('2026-03-16T19:00:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm100-w2',
      threadId: '14',
      sender: 'staff',
      content: 'Hi! Let me check on that for you. For March 18th, we can offer a late checkout until 2 PM at no extra charge.',
      timestamp: new Date('2026-03-16T19:05:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm100-w3',
      threadId: '14',
      sender: 'guest',
      content: 'That works perfectly, thank you! 🙏',
      timestamp: new Date('2026-03-16T19:08:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
  ],
  // Emerson Smith — multi-channel (SMS + WhatsApp + Email)
  '15': [
    {
      id: 'm104',
      threadId: '15',
      sender: 'guest',
      content: 'Hi, I wanted to confirm my reservation for next month.',
      timestamp: new Date('2026-03-16T09:50:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm15-w1',
      threadId: '15',
      sender: 'guest',
      content: 'Hey, do you guys have a spa? I want to book a couples massage for our anniversary',
      timestamp: new Date('2026-03-16T10:15:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm15-w2',
      threadId: '15',
      sender: 'staff',
      content: 'Happy anniversary! Yes, our Serenity Spa is on the 4th floor. For a couples massage I\'d recommend the 90-minute deep tissue — it\'s our most popular. Would you like me to book a time?',
      timestamp: new Date('2026-03-16T10:20:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm15-w3',
      threadId: '15',
      sender: 'guest',
      content: 'That sounds perfect. Can we do Saturday morning around 10?',
      timestamp: new Date('2026-03-16T10:25:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm15-w4',
      threadId: '15',
      sender: 'staff',
      content: 'You\'re all set! Saturday March 22 at 10:00 AM, couples deep tissue massage (90 min). Please arrive 15 minutes early to enjoy the sauna beforehand.',
      timestamp: new Date('2026-03-16T10:30:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm15-e1',
      threadId: '15',
      sender: 'staff',
      content: 'Dear Mr. Smith,\n\nThank you for your reservation at The Grand Ithaca Hotel. We\'re delighted to confirm your upcoming stay:\n\n• Check-in: June 14, 2026\n• Check-out: June 17, 2026\n• Room: Deluxe Suite\n• Rate: Gold Elite Member Rate\n\nAs a Gold Elite member, you\'ll enjoy complimentary breakfast and late checkout upon request.\n\nWe look forward to welcoming you.\n\nBest regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-10T09:00:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm15-e2',
      threadId: '15',
      sender: 'guest',
      content: 'Thanks for the confirmation. Quick question — it\'s our anniversary weekend so I wanted to see if there are any special packages? Wine, flowers, that sort of thing.\n\nAlso is the rooftop restaurant open for dinner on Saturdays?\n\nThanks,\nEmerson',
      timestamp: new Date('2026-03-10T14:00:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm15-e3',
      threadId: '15',
      sender: 'staff',
      content: 'Hi Emerson,\n\nCongratulations! We have a few anniversary options:\n\n• Romance Package ($150) — champagne, chocolate-covered strawberries, rose petals, and a handwritten card\n• Premium Romance ($275) — everything above plus a couples spa credit and late checkout guaranteed\n\nOur rooftop restaurant is open Saturday 5-11 PM. I\'d recommend a reservation — Saturday evenings fill up fast.\n\nShall I add either package to your booking?\n\nBest,\nTheresa Webb\nGuest Services',
      timestamp: new Date('2026-03-10T15:30:00'),
      channel: 'Email',
      status: 'delivered',
    },
  ],
  // +12125550000 — unlinked guest, multi-channel (SMS + Expedia)
  '16': [
    {
      id: 'm105',
      threadId: '16',
      sender: 'guest',
      content: 'Is there availability for this weekend?',
      timestamp: new Date('2026-03-16T09:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm16-s2',
      threadId: '16',
      sender: 'ai',
      content: 'Hi! Yes, we have availability this weekend. Our standard king room starts at $189/night and the deluxe suite is $299/night. Would you like me to check specific dates?',
      timestamp: new Date('2026-03-16T09:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm16-s3',
      threadId: '16',
      sender: 'guest',
      content: 'The king room works. Friday and Saturday nights. How do I book?',
      timestamp: new Date('2026-03-16T09:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm16-s4',
      threadId: '16',
      sender: 'staff',
      content: 'Great choice! You can book directly on our website for the best rate, or I can send you a booking link. Just need your name and email to get started.',
      timestamp: new Date('2026-03-16T09:38:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm16-x1',
      threadId: '16',
      sender: 'guest',
      content: 'Hi, I just made a reservation through Expedia for this Friday-Sunday (itinerary #EXP-2938471). The listing said free cancellation — can you confirm?',
      timestamp: new Date('2026-03-16T11:00:00'),
      channel: 'Expedia',
      status: 'delivered',
    },
    {
      id: 'm16-x2',
      threadId: '16',
      sender: 'staff',
      content: 'Welcome! I can see your Expedia reservation. Yes, it includes free cancellation up to 48 hours before check-in (so by Wednesday 3 PM). After that, the first night is non-refundable.',
      timestamp: new Date('2026-03-16T11:10:00'),
      channel: 'Expedia',
      status: 'delivered',
    },
    {
      id: 'm16-x3',
      threadId: '16',
      sender: 'guest',
      content: 'Perfect, thanks. Also is parking included or is that extra?',
      timestamp: new Date('2026-03-16T11:15:00'),
      channel: 'Expedia',
      status: 'delivered',
    },
  ],
  // Emily Smith's conversation — multi-channel (SMS + Email)
  '1': [
    {
      id: 'm1',
      threadId: '1',
      sender: 'guest',
      content: 'I will arrive late today. My flight is delayed.',
      timestamp: new Date('2026-03-16T17:10:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2',
      threadId: '1',
      sender: 'ai',
      content: 'Thanks for letting us know!',
      timestamp: new Date('2026-03-16T17:25:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm3',
      threadId: '1',
      sender: 'guest',
      content: 'Give me a list of nearby restaurants',
      timestamp: new Date('2026-03-16T18:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm4',
      threadId: '1',
      sender: 'ai',
      content: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
      timestamp: new Date('2026-03-16T18:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // Email thread: reservation confirmation
    {
      id: 'm1-e1',
      threadId: '1',
      sender: 'staff',
      content: 'Dear Ms. Smith,\n\nThank you for choosing The Grand Ithaca Hotel for your upcoming stay. We are pleased to confirm your reservation:\n\n• Check-in: July 15, 2026\n• Check-out: July 18, 2026\n• Room Type: Deluxe King\n• Confirmation: #GIH-2026-4821\n\nPlease let us know if you have any special requests prior to your arrival.\n\nWarm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-14T09:00:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm1-e2',
      threadId: '1',
      sender: 'guest',
      content: 'Hi,\n\nThank you for the confirmation. I was wondering if it would be possible to get an early check-in around 11 AM? My flight arrives at 9:30 AM.\n\nAlso, do you have any gluten-free options for breakfast?\n\nThanks,\nEmily',
      timestamp: new Date('2026-03-14T14:22:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm1-e3',
      threadId: '1',
      sender: 'staff',
      content: 'Hi Emily,\n\nWe\'ll do our best to accommodate early check-in at 11 AM — this is subject to availability, but we\'ve noted your preference.\n\nRegarding breakfast, yes! Our buffet includes a dedicated gluten-free section with fresh fruit, yogurt, eggs, and gluten-free bread and pastries.\n\nLooking forward to welcoming you!\n\nBest,\nTheresa Webb\nGuest Services',
      timestamp: new Date('2026-03-14T16:05:00'),
      channel: 'Email',
      status: 'delivered',
    },
  ],
  // Miguel's conversation — multi-channel (SMS + WhatsApp + Email)
  '2': [
    {
      id: 'm5',
      threadId: '2',
      sender: 'guest',
      content: 'Can I have extra face towels to the room please?',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2-s2',
      threadId: '2',
      sender: 'ai',
      content: 'Of course! I\'ll have housekeeping bring extra face towels to room 206 right away. Is there anything else you need?',
      timestamp: new Date('2026-03-16T10:06:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2-s3',
      threadId: '2',
      sender: 'guest',
      content: 'Actually yes — the minibar is missing water bottles. Can you restock?',
      timestamp: new Date('2026-03-16T10:10:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2-s4',
      threadId: '2',
      sender: 'staff',
      content: 'Absolutely, I\'ll have both the towels and water bottles sent up within 15 minutes.',
      timestamp: new Date('2026-03-16T10:12:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2-w1',
      threadId: '2',
      sender: 'guest',
      content: 'Hi, quick question — is it possible to get a late checkout on Tuesday? My flight isn\'t until 8pm',
      timestamp: new Date('2026-03-16T20:00:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm2-w2',
      threadId: '2',
      sender: 'staff',
      content: 'Hi Miguel! Let me check availability for a late checkout on Tuesday. With an 8 PM flight, would 2 PM work? That gives you plenty of buffer.',
      timestamp: new Date('2026-03-16T20:05:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm2-w3',
      threadId: '2',
      sender: 'guest',
      content: '2pm would be great actually. How much extra is it?',
      timestamp: new Date('2026-03-16T20:08:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm2-w4',
      threadId: '2',
      sender: 'staff',
      content: 'No charge — complimentary late checkout until 2 PM confirmed for Tuesday. Enjoy the rest of your stay!',
      timestamp: new Date('2026-03-16T20:15:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm2-e1',
      threadId: '2',
      sender: 'staff',
      content: 'Dear Mr. Santana,\n\nWelcome to The Grand Ithaca Hotel! We hope you\'re enjoying your stay.\n\nAs a reminder, our complimentary breakfast buffet is available daily from 6:30-10:30 AM in the Garden Room (2nd floor). Your room key grants you access.\n\nThis week\'s special events:\n• Wednesday: Live jazz in the lobby lounge, 7-10 PM\n• Thursday: Wine tasting at the rooftop bar, 6 PM ($45/person)\n• Saturday: Chef\'s table dinner, 7:30 PM (reservation required)\n\nPlease reply if you\'d like us to reserve a spot for any of these.\n\nWarm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-15T08:00:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm2-e2',
      threadId: '2',
      sender: 'guest',
      content: 'The wine tasting sounds great — can you put me down for 2 people on Thursday?\n\nAlso, is there a dress code for the chef\'s table?\n\nThanks,\nMiguel',
      timestamp: new Date('2026-03-15T12:30:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm2-e3',
      threadId: '2',
      sender: 'staff',
      content: 'Hi Miguel,\n\nYou\'re booked for the wine tasting — Thursday at 6 PM, party of 2. Meet at the rooftop bar.\n\nFor the chef\'s table, it\'s smart casual. No shorts or flip-flops, but no need for a jacket. Would you like me to reserve Saturday as well?\n\nBest,\nTheresa Webb',
      timestamp: new Date('2026-03-15T13:00:00'),
      channel: 'Email',
      status: 'delivered',
    },
  ],
  // Brooklyn's conversation — multi-channel (SMS + Booking.com)
  '3': [
    {
      id: 'm6',
      threadId: '3',
      sender: 'guest',
      content: 'What are the check-out procedures?',
      timestamp: new Date('2026-03-16T09:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm7',
      threadId: '3',
      sender: 'ai',
      content: 'Check-out time is 11:00 AM. You can check out at the front desk or use express check-out through the TV in your room.',
      timestamp: new Date('2026-03-16T09:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm8',
      threadId: '3',
      sender: 'guest',
      content: 'Got it, thanks.',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm3-b1',
      threadId: '3',
      sender: 'guest',
      content: 'Hi, I booked through Booking.com (confirmation #BK-9847263). Can I request a room on a higher floor?',
      timestamp: new Date('2026-03-15T14:00:00'),
      channel: 'Booking.com',
      status: 'delivered',
    },
    {
      id: 'm3-b2',
      threadId: '3',
      sender: 'staff',
      content: 'Hi Brooklyn! We\'ve noted your preference for a higher floor. We\'ll do our best to accommodate — your current assignment is room 130 on the 13th floor.',
      timestamp: new Date('2026-03-15T14:20:00'),
      channel: 'Booking.com',
      status: 'delivered',
    },
    {
      id: 'm3-w1',
      threadId: '3',
      sender: 'guest',
      content: 'Hi! I\'m arriving around 3pm today. Is the room going to be ready by then?',
      timestamp: new Date('2026-03-16T11:00:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm3-w2',
      threadId: '3',
      sender: 'ai',
      content: 'Hi Brooklyn! Check-in starts at 3 PM so your room should be ready. If you arrive early, we\'re happy to store your luggage at the front desk.',
      timestamp: new Date('2026-03-16T11:02:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm3-w3',
      threadId: '3',
      sender: 'guest',
      content: 'Great, and can I get a fridge in the room? I have medication that needs to stay cold',
      timestamp: new Date('2026-03-16T11:05:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm3-w4',
      threadId: '3',
      sender: 'staff',
      content: 'Absolutely — we\'ll make sure room 130 has a mini-fridge ready and cleared out for your medication before you arrive.',
      timestamp: new Date('2026-03-16T11:10:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
  ],
  // Marco's conversation
  '4': [
    {
      id: 'm9',
      threadId: '4',
      sender: 'guest',
      content: 'What time will the pool close?',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Kristin's conversation
  '5': [
    {
      id: 'm10',
      threadId: '5',
      sender: 'guest',
      content: 'Is there a gym in the hotel?',
      timestamp: new Date('2026-03-16T09:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm11',
      threadId: '5',
      sender: 'ai',
      content: 'Yes! Our fitness center is on the 2nd floor and is open 24/7 for all guests.',
      timestamp: new Date('2026-03-16T09:46:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm12',
      threadId: '5',
      sender: 'guest',
      content: "Great. That's super helpful.",
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Liam's conversation — multi-channel (SMS + Expedia)
  '6': [
    {
      id: 'm13',
      threadId: '6',
      sender: 'guest',
      content: 'Can you explain the parking options?',
      timestamp: new Date('2026-03-16T09:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm14',
      threadId: '6',
      sender: 'ai',
      content: 'We offer valet parking for $35/day and self-parking for $25/day. Both are available 24/7.',
      timestamp: new Date('2026-03-16T09:22:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm15',
      threadId: '6',
      sender: 'guest',
      content: 'Awesome! That really clears things up.',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm6-x1',
      threadId: '6',
      sender: 'guest',
      content: 'Hello, I booked via Expedia (itinerary #EXP-7291034). I need to modify my reservation to add one more night. Is that possible?',
      timestamp: new Date('2026-03-15T11:00:00'),
      channel: 'Expedia',
      status: 'delivered',
    },
    {
      id: 'm6-x2',
      threadId: '6',
      sender: 'staff',
      content: 'Hi Liam! Since you booked through Expedia, the modification would need to go through them directly. However, I can confirm we have availability for an additional night at the same rate.',
      timestamp: new Date('2026-03-15T11:15:00'),
      channel: 'Expedia',
      status: 'delivered',
    },
    {
      id: 'm6-x3',
      threadId: '6',
      sender: 'guest',
      content: 'OK great, I\'ll update it on Expedia then. Thanks for confirming availability!',
      timestamp: new Date('2026-03-15T11:30:00'),
      channel: 'Expedia',
      status: 'delivered',
    },
  ],
  // Olivia's conversation
  '7': [
    {
      id: 'm16',
      threadId: '7',
      sender: 'guest',
      content: 'What time is breakfast served?',
      timestamp: new Date('2026-03-16T09:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm17',
      threadId: '7',
      sender: 'ai',
      content: 'Our complimentary breakfast buffet is served daily from 6:30 AM to 10:30 AM in the main dining room.',
      timestamp: new Date('2026-03-16T09:02:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm18',
      threadId: '7',
      sender: 'guest',
      content: 'Fantastic! This is exactly what I needed.',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Noah's conversation
  '8': [
    {
      id: 'm19',
      threadId: '8',
      sender: 'guest',
      content: 'Do you have any recommendations for local attractions?',
      timestamp: new Date('2026-03-16T08:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm20',
      threadId: '8',
      sender: 'ai',
      content: "Absolutely! Within walking distance you have the waterfront, several museums, and historic downtown. I can also arrange tours if you're interested.",
      timestamp: new Date('2026-03-16T08:47:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm21',
      threadId: '8',
      sender: 'guest',
      content: 'Perfect! This information is incredibly useful.',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Emma's conversation
  '9': [
    {
      id: 'm22',
      threadId: '9',
      sender: 'guest',
      content: 'Can I request a late checkout?',
      timestamp: new Date('2026-03-16T08:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm23',
      threadId: '9',
      sender: 'ai',
      content: 'Yes, we can accommodate a late checkout until 2:00 PM for an additional $50, subject to availability. Would you like me to arrange that for you?',
      timestamp: new Date('2026-03-16T08:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm24',
      threadId: '9',
      sender: 'guest',
      content: 'Excellent! I appreciate your help with this.',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Priya's conversation
  '17': [
    {
      id: 'm62',
      threadId: '17',
      sender: 'guest',
      content: 'Hi, could you arrange a taxi to the airport for tomorrow at 6 AM?',
      timestamp: new Date('2026-03-16T09:15:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Yuki's conversation
  '18': [
    {
      id: 'm63',
      threadId: '18',
      sender: 'guest',
      content: 'Is there a Japanese restaurant nearby you would recommend?',
      timestamp: new Date('2026-03-16T08:50:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Fatima's conversation — multi-channel (SMS + Email x2 subjects + WhatsApp)
  '19': [
    {
      id: 'm64',
      threadId: '19',
      sender: 'guest',
      content: 'I just arrived and noticed my suite has been upgraded!',
      timestamp: new Date('2026-03-16T09:40:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm65',
      threadId: '19',
      sender: 'staff',
      content: 'Welcome back, Ms. Al-Hassan! As a Diamond Elite member, we upgraded you to the Presidential Suite. We hope you enjoy your stay!',
      timestamp: new Date('2026-03-16T09:42:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm66',
      threadId: '19',
      sender: 'guest',
      content: 'Thank you for the upgrade, the suite is beautiful!',
      timestamp: new Date('2026-03-16T10:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // Email thread 1: Welcome / pre-arrival
    {
      id: 'm19-e1',
      threadId: '19',
      sender: 'staff',
      content: 'Dear Ms. Al-Hassan,\n\nWelcome back! We see you are a returning Diamond Elite guest and we are delighted to host you again.\n\nAs a valued member, you have been upgraded to our Presidential Suite. Your preferred amenities (extra pillows, sparkling water, and fresh orchids) have been arranged.\n\nPlease don\'t hesitate to reach out if there is anything else we can prepare before your arrival.\n\nWith warm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-15T10:00:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm19-e2',
      threadId: '19',
      sender: 'guest',
      content: 'Thank you so much for remembering my preferences! That is wonderful.\n\nOne additional request — could you arrange a car service from the airport? My flight arrives at 8:15 AM on the 16th (Delta DL 1847).\n\nBest,\nFatima',
      timestamp: new Date('2026-03-15T11:30:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm19-e3',
      threadId: '19',
      sender: 'staff',
      content: 'Absolutely, Ms. Al-Hassan!\n\nA black car will be waiting at the arrivals terminal for Delta DL 1847. The driver will have a sign with your name. Estimated drive to the hotel is 25 minutes.\n\nSafe travels!\n\nTheresa Webb\nGuest Services',
      timestamp: new Date('2026-03-15T12:15:00'),
      channel: 'Email',
      status: 'delivered',
    },
    // Email thread 2: Dinner reservation
    {
      id: 'm19-e4',
      threadId: '19',
      sender: 'guest',
      content: 'Hi,\n\nI would like to make a dinner reservation at Il Ristorante Alga for March 17th at 7:30 PM, party of 4. Could you help arrange this?\n\nAlso, one guest has a severe nut allergy — please let the kitchen know.\n\nThank you,\nFatima Al-Hassan',
      timestamp: new Date('2026-03-16T11:00:00'),
      channel: 'Email',
      status: 'delivered',
    },
    {
      id: 'm19-e5',
      threadId: '19',
      sender: 'staff',
      content: 'Hi Fatima,\n\nYour reservation at Il Ristorante Alga is confirmed:\n\n• Date: March 17, 2026\n• Time: 7:30 PM\n• Party size: 4\n• Note: Severe nut allergy communicated to the kitchen\n\nThey have reserved the corner table by the window for your party. Enjoy!\n\nBest,\nTheresa Webb',
      timestamp: new Date('2026-03-16T11:45:00'),
      channel: 'Email',
      status: 'delivered',
    },
    // WhatsApp
    {
      id: 'm19-w1',
      threadId: '19',
      sender: 'guest',
      content: 'Quick question — is the hotel pool heated? Thinking of going for a swim this evening',
      timestamp: new Date('2026-03-16T15:30:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm19-w2',
      threadId: '19',
      sender: 'ai',
      content: 'Yes, our pool is heated to 82°F year-round! It\'s open until 10 PM tonight. Towels are provided poolside.',
      timestamp: new Date('2026-03-16T15:32:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
  ],
  // Lucia's conversation
  '20': [
    {
      id: 'm67',
      threadId: '20',
      sender: 'guest',
      content: 'Can someone bring extra blankets to room 226?',
      timestamp: new Date('2026-03-16T07:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Hiroshi's conversation
  '21': [
    {
      id: 'm68',
      threadId: '21',
      sender: 'guest',
      content: 'The room service menu — is it available after midnight?',
      timestamp: new Date('2026-03-15T23:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm69',
      threadId: '21',
      sender: 'ai',
      content: 'Our room service is available 24 hours. The full menu is in your room, or I can send you a digital copy.',
      timestamp: new Date('2026-03-15T23:46:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Ingrid's conversation
  '22': [
    {
      id: 'm70',
      threadId: '22',
      sender: 'guest',
      content: 'Hi, I left my mobile key in the old room after I switched. Can I get a new one?',
      timestamp: new Date('2026-03-15T16:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm71',
      threadId: '22',
      sender: 'staff',
      content: 'Of course! I\'ve reissued a mobile key for your new room 608. You can also pick up a physical key at the front desk.',
      timestamp: new Date('2026-03-15T16:05:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm72',
      threadId: '22',
      sender: 'guest',
      content: 'Perfect, I will pick up the key at the front desk.',
      timestamp: new Date('2026-03-15T16:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Thomas's conversation
  '23': [
    {
      id: 'm73',
      threadId: '23',
      sender: 'guest',
      content: 'Do you have a business center or somewhere I can print documents?',
      timestamp: new Date('2026-03-16T08:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Rachel's conversation
  '24': [
    {
      id: 'm74',
      threadId: '24',
      sender: 'guest',
      content: 'What are the hours for the rooftop bar?',
      timestamp: new Date('2026-03-15T15:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm75',
      threadId: '24',
      sender: 'ai',
      content: 'The rooftop bar is open daily from 4:00 PM to midnight. Happy hour is 4-6 PM with half-price cocktails!',
      timestamp: new Date('2026-03-15T15:02:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm76',
      threadId: '24',
      sender: 'guest',
      content: 'Thank you, that was very helpful!',
      timestamp: new Date('2026-03-15T15:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Chloe's conversation
  '25': [
    {
      id: 'm77',
      threadId: '25',
      sender: 'guest',
      content: 'Is the spa open on Sundays?',
      timestamp: new Date('2026-03-16T09:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Andre's conversation
  '26': [
    {
      id: 'm78',
      threadId: '26',
      sender: 'guest',
      content: 'The air conditioning in room 124 seems to be blowing warm air.',
      timestamp: new Date('2026-03-15T21:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm79',
      threadId: '26',
      sender: 'staff',
      content: 'Sorry about that! I\'m sending maintenance to check the AC unit right away.',
      timestamp: new Date('2026-03-15T21:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm80',
      threadId: '26',
      sender: 'guest',
      content: 'All good now, the AC is working fine.',
      timestamp: new Date('2026-03-15T22:10:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Maya's conversation
  '27': [
    {
      id: 'm81',
      threadId: '27',
      sender: 'guest',
      content: 'We loved the complimentary breakfast. Thank you!',
      timestamp: new Date('2026-03-16T10:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Sarah Martinez - Archived
  '10': [
    {
      id: 'm25',
      threadId: '10',
      sender: 'guest',
      content: 'Hi! Just checked in. The room looks lovely!',
      timestamp: new Date('2026-03-09T15:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm26',
      threadId: '10',
      sender: 'staff',
      content: 'Welcome Sarah! So glad you like it. Please let us know if you need anything during your stay.',
      timestamp: new Date('2026-03-09T15:22:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm27',
      threadId: '10',
      sender: 'guest',
      content: 'Thank you so much for the wonderful stay! Everything was perfect.',
      timestamp: new Date('2026-03-12T11:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // James Chen - Archived
  '11': [
    {
      id: 'm35',
      threadId: '11',
      sender: 'guest',
      content: "The WiFi in my room isn't working. I need to join a video call in 30 minutes.",
      timestamp: new Date('2026-03-10T14:15:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm36',
      threadId: '11',
      sender: 'staff',
      content: "I'm so sorry about that! Let me get our IT team to your room right away.",
      timestamp: new Date('2026-03-10T14:16:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm42',
      threadId: '11',
      sender: 'guest',
      content: 'All set, thanks for resolving the WiFi issue.',
      timestamp: new Date('2026-03-11T16:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Maria Garcia - Archived
  '12': [
    {
      id: 'm43',
      threadId: '12',
      sender: 'guest',
      content: "Hola! Is it possible to have a late checkout? My flight isn't until 6pm.",
      timestamp: new Date('2026-03-09T09:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm44',
      threadId: '12',
      sender: 'ai',
      content: 'Hi Maria! Yes, we can arrange a late checkout for you. Would 3:00 PM work for your schedule?',
      timestamp: new Date('2026-03-09T09:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm50',
      threadId: '12',
      sender: 'guest',
      content: 'Perfect, the late checkout worked out great. See you next time!',
      timestamp: new Date('2026-03-10T14:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
  // Robert Thompson - Archived
  '13': [
    {
      id: 'm51',
      threadId: '13',
      sender: 'guest',
      content: "I'd like to request a room upgrade if possible. Staying for 4 nights.",
      timestamp: new Date('2026-03-05T16:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm52',
      threadId: '13',
      sender: 'staff',
      content: "Good evening Mr. Thompson! As a Diamond Elite member, we'd be happy to upgrade you to a junior suite at no additional charge.",
      timestamp: new Date('2026-03-05T16:05:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm61',
      threadId: '13',
      sender: 'guest',
      content: 'Appreciate all your help with the room upgrade and restaurant reservations!',
      timestamp: new Date('2026-03-09T10:15:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],
};

export const mockEmailThreads: EmailThread[] = [
  {
    id: 'email-1-confirm',
    subject: 'Reservation Confirmation #GIH-2026-4821',
    parentThreadId: '1',
  },
  {
    id: 'email-15-confirm',
    subject: 'Reservation Confirmation — Gold Elite Stay',
    parentThreadId: '15',
  },
  {
    id: 'email-2-welcome',
    subject: 'Welcome to The Grand Ithaca — Weekly Events',
    parentThreadId: '2',
  },
  {
    id: 'email-19-welcome',
    subject: 'Welcome Back, Ms. Al-Hassan — Diamond Elite',
    parentThreadId: '19',
  },
  {
    id: 'email-19-dinner',
    subject: 'Dinner Reservation — Il Ristorante Alga, March 17',
    parentThreadId: '19',
  },
];

export function getEmailThreadsForThread(threadId: string): EmailThread[] {
  return mockEmailThreads.filter((et) => et.parentThreadId === threadId);
}

export function getChannelsForThread(threadId: string): Set<import('./types').MessageChannel> {
  const messages = mockMessages[threadId] || [];
  const channels = new Set<import('./types').MessageChannel>();
  for (const msg of messages) {
    if (msg.channel) channels.add(msg.channel);
  }
  return channels;
}
