/**
 * Messaging Mock Data
 *
 * Thread and message data that references canonical guests and reservations.
 */

import { Thread, Message, EmailThread } from './types';

/**
 * Mock threads - link to canonical guest and reservation IDs
 */
export const mockThreads: Thread[] = [
  // Multi-reservation thread (1 auto-linked + 3 manually linked)
  {
    id: '14',
    contactNumber: '+16507665555',
    linkedReservationIds: ['res-john-jul', 'res-james-jul', 'res-ethan-jul', 'res-liam-aug'],
    lastMessage: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: true,
    status: 'inbox',
  },
  // Single manually-linked reservation (phone doesn't match)
  {
    id: '15',
    contactNumber: '+13305559999',
    linkedReservationIds: ['res-emerson-jun'],
    lastMessage: 'Hi, I wanted to confirm my reservation for next month.',
    lastMessageAt: new Date('2026-03-16T09:50:00'),
    isUnread: true,
    status: 'inbox',
  },
  // Empty thread (no linked reservations)
  {
    id: '16',
    contactNumber: '+12125550000',
    linkedReservationIds: [],
    lastMessage: 'Is there availability for this weekend?',
    lastMessageAt: new Date('2026-03-16T09:30:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '19',
    contactNumber: '+15005550043',
    linkedReservationIds: ['res-fatima-nov'],
    lastMessage: 'Thank you for the upgrade, the suite is beautiful!',
    lastMessageAt: new Date('2026-03-16T10:00:00'),
    isUnread: false,
    status: 'inbox',
  },
  // Single auto-linked threads (existing guests — phone matches contactNumber)
  {
    id: '1',
    contactNumber: '+15005550012',
    linkedReservationIds: ['res-emily-jul'],
    lastMessage: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '2',
    contactNumber: '+15005550013',
    linkedReservationIds: ['res-miguel-nov'],
    lastMessage: 'Can I have extra face towels to the room please?',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '3',
    contactNumber: '+15005550014',
    linkedReservationIds: ['res-brooklyn-nov'],
    lastMessage: 'Got it, thanks.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '4',
    contactNumber: '+15005550015',
    linkedReservationIds: ['res-marco-nov'],
    lastMessage: 'What time will the pool close?',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '5',
    contactNumber: '+15005550016',
    linkedReservationIds: ['res-kristin-nov'],
    lastMessage: "Great. That's super helpful.",
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '6',
    contactNumber: '+15005550017',
    linkedReservationIds: ['res-liam-nov'],
    lastMessage: 'Awesome! That really clears things up.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '7',
    contactNumber: '+15005550018',
    linkedReservationIds: ['res-olivia-nov'],
    lastMessage: 'Fantastic! This is exactly what I needed.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '8',
    contactNumber: '+15005550019',
    linkedReservationIds: ['res-noah-nov'],
    lastMessage: 'Perfect! This information is incredibly useful.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '9',
    contactNumber: '+15005550024',
    linkedReservationIds: ['res-emma-nov'],
    lastMessage: 'Excellent! I appreciate your help with this.',
    lastMessageAt: new Date('2026-03-16T10:04:00'),
    isUnread: false,
    status: 'inbox',
  },
  // New guest threads
  {
    id: '17',
    contactNumber: '+15005550040',
    linkedReservationIds: ['res-priya-nov'],
    lastMessage: 'Could you arrange a taxi to the airport for tomorrow at 6 AM?',
    lastMessageAt: new Date('2026-03-16T09:15:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '18',
    contactNumber: '+15005550042',
    linkedReservationIds: ['res-yuki-nov'],
    lastMessage: 'Is there a Japanese restaurant nearby you would recommend?',
    lastMessageAt: new Date('2026-03-16T08:50:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '20',
    contactNumber: '+15005550045',
    linkedReservationIds: ['res-lucia-nov'],
    lastMessage: 'Can someone bring extra blankets to room 226?',
    lastMessageAt: new Date('2026-03-16T07:30:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '21',
    contactNumber: '+15005550050',
    linkedReservationIds: ['res-hiroshi-nov'],
    lastMessage: 'The room service menu — is it available after midnight?',
    lastMessageAt: new Date('2026-03-15T23:45:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '22',
    contactNumber: '+15005550057',
    linkedReservationIds: ['res-ingrid-nov'],
    lastMessage: 'Perfect, I will pick up the key at the front desk.',
    lastMessageAt: new Date('2026-03-15T16:20:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '23',
    contactNumber: '+15005550063',
    linkedReservationIds: ['res-thomas-k-nov'],
    lastMessage: 'Do you have a business center or somewhere I can print documents?',
    lastMessageAt: new Date('2026-03-16T08:00:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '24',
    contactNumber: '+15005550064',
    linkedReservationIds: ['res-rachel-nov'],
    lastMessage: 'Thank you, that was very helpful!',
    lastMessageAt: new Date('2026-03-15T15:30:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '25',
    contactNumber: '+15005550066',
    linkedReservationIds: ['res-chloe-nov'],
    lastMessage: 'Is the spa open on Sundays?',
    lastMessageAt: new Date('2026-03-16T09:00:00'),
    isUnread: true,
    status: 'inbox',
  },
  {
    id: '26',
    contactNumber: '+15005550067',
    linkedReservationIds: ['res-andre-nov'],
    lastMessage: 'All good now, the AC is working fine.',
    lastMessageAt: new Date('2026-03-15T22:10:00'),
    isUnread: false,
    status: 'inbox',
  },
  {
    id: '27',
    contactNumber: '+15005550068',
    linkedReservationIds: ['res-maya-nov'],
    lastMessage: 'We loved the complimentary breakfast. Thank you!',
    lastMessageAt: new Date('2026-03-16T10:30:00'),
    isUnread: false,
    status: 'inbox',
  },
  // Archived conversations
  {
    id: '10',
    contactNumber: '+15005550020',
    linkedReservationIds: ['res-sarah-nov'],
    lastMessage: 'Thank you so much for the wonderful stay! Everything was perfect.',
    lastMessageAt: new Date('2026-03-12T11:30:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '11',
    contactNumber: '+15005550021',
    linkedReservationIds: ['res-james-nov'],
    lastMessage: 'All set, thanks for resolving the WiFi issue.',
    lastMessageAt: new Date('2026-03-11T16:45:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '12',
    contactNumber: '+15005550022',
    linkedReservationIds: ['res-maria-nov'],
    lastMessage: 'Perfect, the late checkout worked out great. See you next time!',
    lastMessageAt: new Date('2026-03-10T14:20:00'),
    isUnread: false,
    status: 'archived',
  },
  {
    id: '13',
    contactNumber: '+15005550023',
    linkedReservationIds: ['res-robert-nov'],
    lastMessage: 'Appreciate all your help with the room upgrade and restaurant reservations!',
    lastMessageAt: new Date('2026-03-09T10:15:00'),
    isUnread: false,
    status: 'archived',
  },
];

/**
 * Mock messages - organized by thread ID
 */
export const mockMessages: Record<string, Message[]> = {
  // ===== JOHN SMITH (thread 14) — Group coordinator, SMS + WhatsApp + Email =====
  // Three email threads deliberately INTERWOVEN in time (Mar 10-14) — the
  // stress case for the unified email view (subjects alternate chronologically).
  '14': [
    // J1: Room block confirmation (GJ) — Mar 10, 11, 13
    {
      id: 'm14-e1',
      threadId: '14',
      sender: 'staff',
      content: 'Dear Mr. Smith,\n\nYour group room block at The Grand Ithaca Hotel is confirmed:\n\n• Confirmation: #GRP-2026-118\n• Rooms: 4\n• Check-in: March 14, 2026\n• Check-out: March 17, 2026\n\nPlease reply with your rooming list so we can assign each reservation.\n\nWarm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-10T09:00:00'),
      channel: 'Email',
      emailThreadId: 'email-14-roomblock',
      isGuestJourney: true,
      status: 'delivered',
    },
    {
      id: 'm14-e2',
      threadId: '14',
      sender: 'guest',
      content: 'Thanks! Rooming list: myself (John Smith), James Brady, Ethan Parker, and Liam Carter. Can you put each reservation under their name?\n\nBest,\nJohn',
      timestamp: new Date('2026-03-11T08:30:00'),
      channel: 'Email',
      emailThreadId: 'email-14-roomblock',
      status: 'delivered',
    },
    // J2: Direct billing — Mar 11, 12, 13
    {
      id: 'm14-e6',
      threadId: '14',
      sender: 'guest',
      content: 'Hi — separate question. We\'d like to set up direct billing to Meridian Consulting for all four rooms. What do you need from us?\n\nJohn',
      timestamp: new Date('2026-03-11T09:45:00'),
      channel: 'Email',
      emailThreadId: 'email-14-billing',
      status: 'delivered',
    },
    {
      id: 'm14-e3',
      threadId: '14',
      sender: 'staff',
      content: 'Hi John,\n\nAll four reservations are now assigned:\n\n• John Smith\n• James Brady\n• Ethan Parker\n• Liam Carter\n\nEach guest will check in under their own name.\n\nBest,\nTheresa Webb\nGuest Services',
      timestamp: new Date('2026-03-11T14:00:00'),
      channel: 'Email',
      emailThreadId: 'email-14-roomblock',
      status: 'delivered',
    },
    {
      id: 'm14-e7',
      threadId: '14',
      sender: 'staff',
      content: 'Hi John,\n\nFor direct billing we need a completed credit authorization form from Meridian Consulting, ideally 48 hours before arrival. I\'ve attached the form — accounting will confirm once it\'s processed.\n\nBest,\nTheresa Webb',
      timestamp: new Date('2026-03-12T09:30:00'),
      channel: 'Email',
      emailThreadId: 'email-14-billing',
      status: 'delivered',
    },
    // J3: Meeting room — Mar 12, 14
    {
      id: 'm14-e9',
      threadId: '14',
      sender: 'guest',
      content: 'One more thing — we need a small meeting room Saturday morning (March 15), 9–11 AM, for the four of us. Ideally with a screen we can plug a laptop into.\n\nJohn',
      timestamp: new Date('2026-03-12T11:00:00'),
      channel: 'Email',
      emailThreadId: 'email-14-meeting',
      status: 'delivered',
    },
    {
      id: 'm14-e10',
      threadId: '14',
      sender: 'staff',
      content: 'Hi John,\n\nBoardroom B is available March 15, 9–11 AM. It seats 8 and has a 65" screen with HDMI. Coffee service is optional at $40.\n\nShall I book it?\n\nBest,\nTheresa Webb',
      timestamp: new Date('2026-03-12T13:30:00'),
      channel: 'Email',
      emailThreadId: 'email-14-meeting',
      status: 'delivered',
    },
    {
      id: 'm14-e4',
      threadId: '14',
      sender: 'guest',
      content: 'Update on the room block — we\'ll have two rental cars with us. Can you arrange parking for both?\n\nJohn',
      timestamp: new Date('2026-03-13T10:00:00'),
      channel: 'Email',
      emailThreadId: 'email-14-roomblock',
      status: 'delivered',
    },
    {
      id: 'm14-e5',
      threadId: '14',
      sender: 'staff',
      content: 'Hi John,\n\nTwo parking spots are reserved for your group ($35/night each, added to the master folio). Just give the plate numbers at check-in.\n\nBest,\nTheresa Webb',
      timestamp: new Date('2026-03-13T11:15:00'),
      channel: 'Email',
      emailThreadId: 'email-14-roomblock',
      status: 'delivered',
    },
    {
      id: 'm14-e8',
      threadId: '14',
      sender: 'guest',
      content: 'Form submitted to accounting this afternoon — can you confirm it went through?\n\nJohn',
      timestamp: new Date('2026-03-13T16:30:00'),
      channel: 'Email',
      emailThreadId: 'email-14-billing',
      status: 'delivered',
    },
    {
      id: 'm14-e11',
      threadId: '14',
      sender: 'guest',
      content: 'Boardroom B confirmed, and yes to the coffee service please.\n\nJohn',
      timestamp: new Date('2026-03-14T08:00:00'),
      channel: 'Email',
      emailThreadId: 'email-14-meeting',
      status: 'delivered',
    },
    {
      id: 'm14-e12',
      threadId: '14',
      sender: 'staff',
      content: 'Booked! Boardroom B, March 15, 9–11 AM with coffee service for four. You\'re all set.\n\nBest,\nTheresa Webb',
      timestamp: new Date('2026-03-14T09:00:00'),
      channel: 'Email',
      emailThreadId: 'email-14-meeting',
      status: 'delivered',
    },
    {
      id: 'm100',
      threadId: '14',
      sender: 'guest',
      content: 'Hi, this is John Smith. I have a group of 4 rooms arriving this Friday (Mar 14). Can you confirm all rooms are on the same floor?',
      timestamp: new Date('2026-03-12T14:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm101',
      threadId: '14',
      sender: 'staff',
      content: 'Hi John! I can see your group booking. Let me check floor assignments. Currently we have rooms 502, 504, 506, and 510 — all on the 5th floor.',
      timestamp: new Date('2026-03-12T14:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm102',
      threadId: '14',
      sender: 'guest',
      content: 'Perfect. One more thing — James and Ethan are flying in late, probably around 11pm. Can you hold their rooms?',
      timestamp: new Date('2026-03-12T15:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm103',
      threadId: '14',
      sender: 'staff',
      content: 'Absolutely, all rooms are guaranteed for late arrival. No worries there. Keys will be ready at the front desk whenever they get in.',
      timestamp: new Date('2026-03-12T15:05:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm104',
      threadId: '14',
      sender: 'guest',
      content: 'Great. We all checked in, rooms are good. Quick question — any restaurant recs for a group dinner tonight?',
      timestamp: new Date('2026-03-15T18:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm105',
      threadId: '14',
      sender: 'ai',
      content: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
      timestamp: new Date('2026-03-15T18:22:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // WhatsApp messages — late checkout follow-up
    {
      id: 'm100-w1',
      threadId: '14',
      sender: 'guest',
      content: 'Hey, quick one — any chance we can get late checkout on Sunday for all 4 rooms? We have a 4pm flight',
      timestamp: new Date('2026-03-16T09:30:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm100-w2',
      threadId: '14',
      sender: 'staff',
      content: 'Hi John! Let me check availability for all four rooms. I can confirm late checkout until 2 PM for rooms 502, 504, and 506. Room 510 can do 1 PM — there\'s an incoming reservation that evening.',
      timestamp: new Date('2026-03-16T09:45:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm100-w3',
      threadId: '14',
      sender: 'guest',
      content: 'That works for us. 1pm is fine for 510. Thanks! 🙏',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
  ],

  // ===== EMERSON SMITH (thread 15) — Anniversary planner, Email + WhatsApp + SMS =====
  '15': [
    // Email: early March — confirmation + anniversary inquiry
    {
      id: 'm15-e1',
      threadId: '15',
      sender: 'staff',
      content: 'Dear Mr. Smith,\n\nThank you for your reservation at The Grand Ithaca Hotel. We\'re delighted to confirm your upcoming stay:\n\n• Check-in: June 14, 2026\n• Check-out: June 17, 2026\n• Room: Deluxe Suite\n• Rate: Gold Elite Member Rate\n\nAs a Gold Elite member, you\'ll enjoy complimentary breakfast and late checkout upon request.\n\nWe look forward to welcoming you.\n\nBest regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-10T09:00:00'),
      channel: 'Email',
      emailThreadId: 'email-15-confirm',
      isGuestJourney: true,
      status: 'delivered',
    },
    {
      id: 'm15-e2',
      threadId: '15',
      sender: 'guest',
      content: 'Thanks for the confirmation. Quick question — it\'s our anniversary weekend so I wanted to see if there are any special packages? Wine, flowers, that sort of thing.\n\nAlso is the rooftop restaurant open for dinner on Saturdays?\n\nThanks,\nEmerson',
      timestamp: new Date('2026-03-10T14:00:00'),
      channel: 'Email',
      emailThreadId: 'email-15-confirm',
      status: 'delivered',
    },
    {
      id: 'm15-e3',
      threadId: '15',
      sender: 'staff',
      content: 'Hi Emerson,\n\nCongratulations! We have a few anniversary options:\n\n• Romance Package ($150) — champagne, chocolate-covered strawberries, rose petals, and a handwritten card\n• Premium Romance ($275) — everything above plus a couples spa credit and late checkout guaranteed\n\nOur rooftop restaurant is open Saturday 5-11 PM. I\'d recommend a reservation — Saturday evenings fill up fast.\n\nShall I add either package to your booking?\n\nBest,\nTheresa Webb\nGuest Services',
      timestamp: new Date('2026-03-10T15:30:00'),
      channel: 'Email',
      emailThreadId: 'email-15-confirm',
      status: 'delivered',
    },
    // WhatsApp: mid-March — spa booking follow-up
    {
      id: 'm15-w1',
      threadId: '15',
      sender: 'guest',
      content: 'Hey, do you guys have a spa? I want to book a couples massage for our anniversary weekend in June',
      timestamp: new Date('2026-03-14T10:15:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm15-w2',
      threadId: '15',
      sender: 'staff',
      content: 'Happy anniversary! Yes, our Serenity Spa is on the 4th floor. For a couples massage I\'d recommend the 90-minute deep tissue — it\'s our most popular. Would you like me to book a time for your stay (Jun 14-17)?',
      timestamp: new Date('2026-03-14T10:20:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm15-w3',
      threadId: '15',
      sender: 'guest',
      content: 'That sounds perfect. Can we do Saturday morning around 10?',
      timestamp: new Date('2026-03-14T10:25:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm15-w4',
      threadId: '15',
      sender: 'staff',
      content: 'You\'re all set! Saturday June 15 at 10:00 AM, couples deep tissue massage (90 min). Please arrive 15 minutes early to enjoy the sauna beforehand. ✨',
      timestamp: new Date('2026-03-14T10:30:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    // SMS: quick parking question
    {
      id: 'm104',
      threadId: '15',
      sender: 'guest',
      content: 'Hi, I wanted to confirm my reservation for next month. Also quick q — is parking included or extra?',
      timestamp: new Date('2026-03-16T09:50:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm15-s2',
      threadId: '15',
      sender: 'ai',
      content: 'Hi Emerson! Your June 14-17 reservation is confirmed. Regarding parking: self-parking is $25/day and valet is $35/day. As a Gold Elite member, we can offer complimentary self-parking. Want me to add that?',
      timestamp: new Date('2026-03-16T09:52:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== +12125550000 (thread 16) — Walk-in inquiry, SMS + Expedia =====
  '16': [
    {
      id: 'm105',
      threadId: '16',
      sender: 'guest',
      content: 'Is there availability for this weekend?',
      timestamp: new Date('2026-03-16T09:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm16-s2',
      threadId: '16',
      sender: 'ai',
      content: 'Hi! Yes, we have availability this weekend. Our standard king room starts at $189/night and the deluxe suite is $299/night. Would you like me to check specific dates?',
      timestamp: new Date('2026-03-16T09:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm16-s3',
      threadId: '16',
      sender: 'guest',
      content: 'The king room works. Friday and Saturday nights. Let me book through Expedia though, I have credits there.',
      timestamp: new Date('2026-03-16T09:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm16-s4',
      threadId: '16',
      sender: 'staff',
      content: 'No problem at all! Book through Expedia and we\'ll see the reservation come in. Feel free to message us here if you need anything before or during your stay.',
      timestamp: new Date('2026-03-16T09:38:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // Expedia: followed up by booking on Expedia
    {
      id: 'm16-x1',
      threadId: '16',
      sender: 'guest',
      content: 'Hi, I just made a reservation through Expedia for this Friday-Sunday (itinerary #EXP-2938471). The listing said free cancellation — can you confirm the cutoff date?',
      timestamp: new Date('2026-03-16T11:00:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    {
      id: 'm16-x2',
      threadId: '16',
      sender: 'staff',
      content: 'Welcome! I can see your Expedia reservation. Yes, free cancellation applies up to 48 hours before check-in (so by Wednesday March 19 at 3 PM). After that, the first night is non-refundable.',
      timestamp: new Date('2026-03-16T11:10:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    {
      id: 'm16-x3',
      threadId: '16',
      sender: 'guest',
      content: 'Perfect, thanks. One more — is parking included or is that extra?',
      timestamp: new Date('2026-03-16T11:15:00'),
      channel: 'OTA',
      status: 'delivered',
    },
  ],

  // ===== EMILY SMITH (thread 1) — Corporate repeat guest, Email (pre-stay) + SMS (mid-stay) =====
  '1': [
    // Email: Mar 12-13 pre-stay exchange
    {
      id: 'm1-e1',
      threadId: '1',
      sender: 'staff',
      content: 'Dear Ms. Smith,\n\nThank you for choosing The Grand Ithaca Hotel for your upcoming stay. We are pleased to confirm your reservation:\n\n• Check-in: March 15, 2026\n• Check-out: March 18, 2026\n• Room Type: Deluxe King (Room 153)\n• Confirmation: #GIH-2026-4821\n\nAs a Diamond Elite member, you\'ll enjoy complimentary breakfast, room upgrade (subject to availability), and express check-in.\n\nPlease let us know if you have any special requests prior to your arrival.\n\nWarm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-12T09:00:00'),
      channel: 'Email',
      emailThreadId: 'email-1-confirm',
      isGuestJourney: true,
      status: 'delivered',
    },
    {
      id: 'm1-e2',
      threadId: '1',
      sender: 'guest',
      content: 'Hi,\n\nThank you for the confirmation. I was wondering if it would be possible to get an early check-in around 11 AM? My flight arrives at 9:30.\n\nAlso, could you have the room stocked with still water and some fresh fruit? I have meetings all afternoon and won\'t have time to step out.\n\nThanks,\nEmily',
      timestamp: new Date('2026-03-12T14:22:00'),
      channel: 'Email',
      emailThreadId: 'email-1-confirm',
      status: 'delivered',
    },
    {
      id: 'm1-e3',
      threadId: '1',
      sender: 'staff',
      content: 'Hi Emily,\n\nWe\'ll do our best to accommodate early check-in at 11 AM — we\'ve flagged your room for priority cleaning. As a Diamond Elite member, early check-in is complimentary when available.\n\nWe\'ll have still water (Acqua Panna) and a fresh fruit plate ready in the room.\n\nSafe travels and see you Saturday!\n\nBest,\nTheresa Webb\nGuest Services',
      timestamp: new Date('2026-03-13T08:45:00'),
      channel: 'Email',
      emailThreadId: 'email-1-confirm',
      status: 'delivered',
    },
    // SMS: Mar 15-16 mid-stay
    {
      id: 'm1',
      threadId: '1',
      sender: 'guest',
      content: 'Checked in! Room is great. Quick q — any restaurant recs within walking distance for a business dinner tonight? Party of 3.',
      timestamp: new Date('2026-03-15T16:10:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2',
      threadId: '1',
      sender: 'ai',
      content: "Here are some nearby restaurant recommendations: Ithaca Ale House, Komonz Grill, MIX, Red's Place, and Chili's Grill & Bar. The hotel also recommends Il Ristorante Alga, Coltivare, Moosewood Restaurant, and Gola Osteria. Let me know if you need more assistance!",
      timestamp: new Date('2026-03-15T16:12:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm3',
      threadId: '1',
      sender: 'guest',
      content: 'Can you make a reservation at Coltivare for 7:30pm tonight? 3 people, Emily Smith.',
      timestamp: new Date('2026-03-15T16:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm4',
      threadId: '1',
      sender: 'staff',
      content: 'Done! Coltivare, tonight at 7:30 PM, party of 3 under Emily Smith. It\'s about a 5-minute walk from the hotel — turn left out the lobby and it\'s on the corner of State Street.',
      timestamp: new Date('2026-03-15T16:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm1-s5',
      threadId: '1',
      sender: 'guest',
      content: 'Hi, can I get room service? A club sandwich and a sparkling water to room 153.',
      timestamp: new Date('2026-03-16T09:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm1-s6',
      threadId: '1',
      sender: 'ai',
      content: 'Absolutely! Club sandwich and sparkling water coming to room 153. Estimated delivery: 20-25 minutes. Anything else?',
      timestamp: new Date('2026-03-16T09:47:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm1-s7',
      threadId: '1',
      sender: 'guest',
      content: 'That\'s it, thanks!',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== MIGUEL (thread 2) — In-house guest, Email + SMS + WhatsApp =====
  '2': [
    // Email: welcome email on arrival day
    {
      id: 'm2-e1',
      threadId: '2',
      sender: 'staff',
      content: 'Dear Mr. Santana,\n\nWelcome to The Grand Ithaca Hotel! We hope you enjoy your stay in room 206.\n\nAs a reminder, our complimentary breakfast buffet is available daily from 6:30-10:30 AM in the Garden Room (2nd floor). Your room key grants you access.\n\nThis week\'s special events:\n• Sunday: Live jazz in the lobby lounge, 7-10 PM\n• Monday: Wine tasting at the rooftop bar, 6 PM ($45/person)\n• Wednesday: Chef\'s table dinner, 7:30 PM (reservation required)\n\nPlease reply if you\'d like us to reserve a spot for any of these.\n\nWarm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-15T08:00:00'),
      channel: 'Email',
      emailThreadId: 'email-2-welcome',
      isGuestJourney: true,
      status: 'delivered',
    },
    {
      id: 'm2-e2',
      threadId: '2',
      sender: 'guest',
      content: 'The wine tasting sounds great — can you put me down for 2 people on Monday?\n\nAlso, is there a dress code for the chef\'s table?\n\nThanks,\nMiguel',
      timestamp: new Date('2026-03-15T12:30:00'),
      channel: 'Email',
      emailThreadId: 'email-2-welcome',
      status: 'delivered',
    },
    {
      id: 'm2-e3',
      threadId: '2',
      sender: 'staff',
      content: 'Hi Miguel,\n\nYou\'re booked for the wine tasting — Monday at 6 PM, party of 2. Meet at the rooftop bar.\n\nFor the chef\'s table, it\'s smart casual. No shorts or flip-flops, but no need for a jacket. Would you like me to reserve Wednesday as well?\n\nBest,\nTheresa Webb',
      timestamp: new Date('2026-03-15T13:00:00'),
      channel: 'Email',
      emailThreadId: 'email-2-welcome',
      status: 'delivered',
    },
    // SMS: mid-stay immediate needs
    {
      id: 'm5',
      threadId: '2',
      sender: 'guest',
      content: 'Can I have extra face towels to the room please?',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2-s2',
      threadId: '2',
      sender: 'ai',
      content: 'Of course! I\'ll have housekeeping bring extra face towels to room 206 right away. Is there anything else you need?',
      timestamp: new Date('2026-03-16T10:06:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2-s3',
      threadId: '2',
      sender: 'guest',
      content: 'Actually yes — the minibar is missing water bottles. Can you restock?',
      timestamp: new Date('2026-03-16T10:10:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm2-s4',
      threadId: '2',
      sender: 'staff',
      content: 'Absolutely, I\'ll have both the towels and water bottles sent up within 15 minutes.',
      timestamp: new Date('2026-03-16T10:12:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // WhatsApp: late checkout request
    {
      id: 'm2-w1',
      threadId: '2',
      sender: 'guest',
      content: 'Hi, quick question — is it possible to get a late checkout on Tuesday? My flight isn\'t until 8pm',
      timestamp: new Date('2026-03-16T20:00:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm2-w2',
      threadId: '2',
      sender: 'staff',
      content: 'Hi Miguel! Let me check availability for a late checkout on Tuesday. With an 8 PM flight, would 2 PM work? That gives you plenty of buffer for the airport.',
      timestamp: new Date('2026-03-16T20:05:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm2-w3',
      threadId: '2',
      sender: 'guest',
      content: '2pm would be great actually. How much extra is it?',
      timestamp: new Date('2026-03-16T20:08:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm2-w4',
      threadId: '2',
      sender: 'staff',
      content: 'No charge — complimentary late checkout until 2 PM confirmed for Tuesday. Enjoy the rest of your stay! 🙌',
      timestamp: new Date('2026-03-16T20:15:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
  ],

  // ===== BROOKLYN SIMMONS (thread 3) — OTA guest, Booking.com + WhatsApp + SMS =====
  '3': [
    // Booking.com: pre-stay (Mar 10-11, before check-in Mar 14)
    {
      id: 'm3-b1',
      threadId: '3',
      sender: 'guest',
      content: 'Hi, I booked through Booking.com (confirmation #BK-9847263). Can I request a room on a higher floor? I\'m a light sleeper and prefer to be away from street noise.',
      timestamp: new Date('2026-03-10T14:00:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    {
      id: 'm3-b2',
      threadId: '3',
      sender: 'staff',
      content: 'Hi Brooklyn! We\'ve noted your preference for a higher floor. We\'ll do our best to accommodate — your current assignment is room 130, which is on the quiet side of the building. I\'ll flag this for a higher floor if one opens up before your arrival.',
      timestamp: new Date('2026-03-10T14:20:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    {
      id: 'm3-b3',
      threadId: '3',
      sender: 'guest',
      content: 'That works, thanks! Also — does the room have a fridge? I have medication that needs refrigeration.',
      timestamp: new Date('2026-03-11T09:30:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    {
      id: 'm3-b4',
      threadId: '3',
      sender: 'staff',
      content: 'Yes, all our rooms include a mini-fridge. We\'ll make sure it\'s cleared and ready for your medication when you arrive. Is there anything else we can prepare?',
      timestamp: new Date('2026-03-11T09:45:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    // WhatsApp: day-of arrival questions (Mar 14)
    {
      id: 'm3-w1',
      threadId: '3',
      sender: 'guest',
      content: 'Hi! I\'m arriving around 3pm today. Will the room be ready by then? 🙏',
      timestamp: new Date('2026-03-14T11:00:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm3-w2',
      threadId: '3',
      sender: 'ai',
      content: 'Hi Brooklyn! Check-in starts at 3 PM so your room should be ready. If you arrive a few minutes early, we\'re happy to store your luggage at the front desk while you wait.',
      timestamp: new Date('2026-03-14T11:02:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm3-w3',
      threadId: '3',
      sender: 'guest',
      content: 'Perfect, thanks! And just confirming — the fridge will be cleared for my medication right?',
      timestamp: new Date('2026-03-14T11:05:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm3-w4',
      threadId: '3',
      sender: 'staff',
      content: 'Confirmed! The mini-fridge in room 130 is cleared and set to the right temperature for medication storage. See you at 3! 👍',
      timestamp: new Date('2026-03-14T11:10:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    // SMS: during stay, checkout question (Mar 16)
    {
      id: 'm6',
      threadId: '3',
      sender: 'guest',
      content: 'What are the check-out procedures? Can I do it from the room or do I need to go to the desk?',
      timestamp: new Date('2026-03-16T09:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm7',
      threadId: '3',
      sender: 'ai',
      content: 'Check-out time is 11:00 AM. You can check out at the front desk, use express check-out through the TV in your room, or simply leave your key in the room and we\'ll email your receipt.',
      timestamp: new Date('2026-03-16T09:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm8',
      threadId: '3',
      sender: 'guest',
      content: 'Got it, thanks.',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // Email: GJ upsell, outbound-only (lives in the Email tab's Sent view)
    {
      id: 'm3-e1',
      threadId: '3',
      sender: 'staff',
      content: 'Dear Ms. Simmons,\n\nYour stay is coming up! Make it special with a few add-ons:\n\n• Spa day pass — $65\n• Guaranteed late checkout (2 PM) — $30\n• Welcome wine & cheese board — $45\n\nReply to this email or tap the link in your check-in invite to add any of these to your stay.\n\nWarm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-13T10:00:00'),
      channel: 'Email',
      emailThreadId: 'email-3-upsell',
      isGuestJourney: true,
      status: 'delivered',
    },
  ],

  // ===== MARCO (thread 4) — Simple SMS =====
  '4': [
    {
      id: 'm9',
      threadId: '4',
      sender: 'guest',
      content: 'What time will the pool close?',
      timestamp: new Date('2026-03-16T10:04:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== KRISTIN (thread 5) — Simple SMS =====
  '5': [
    {
      id: 'm10',
      threadId: '5',
      sender: 'guest',
      content: 'Is there a gym in the hotel?',
      timestamp: new Date('2026-03-15T09:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm11',
      threadId: '5',
      sender: 'ai',
      content: 'Yes! Our fitness center is on the 2nd floor and is open 24/7 for all guests. Towels and water are provided.',
      timestamp: new Date('2026-03-15T09:46:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm12',
      threadId: '5',
      sender: 'guest',
      content: "Great. That's super helpful.",
      timestamp: new Date('2026-03-15T09:50:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== LIAM JOHNSON (thread 6) — OTA guest, Expedia + SMS =====
  '6': [
    // Expedia: pre-stay reservation modification (Mar 12-13)
    {
      id: 'm6-x1',
      threadId: '6',
      sender: 'guest',
      content: 'Hello, I booked via Expedia (itinerary #EXP-7291034). I need to modify my reservation to add one more night — arriving the 15th now instead of the 16th. Is that possible?',
      timestamp: new Date('2026-03-12T11:00:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    {
      id: 'm6-x2',
      threadId: '6',
      sender: 'staff',
      content: 'Hi Liam! Since you booked through Expedia, the modification would need to go through them directly. However, I can confirm we have availability for March 15th at the same rate. Go ahead and update on Expedia and it\'ll sync on our end.',
      timestamp: new Date('2026-03-12T11:15:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    {
      id: 'm6-x3',
      threadId: '6',
      sender: 'guest',
      content: 'Done, updated it. One more question — what are the parking options? I\'m driving up from Philly.',
      timestamp: new Date('2026-03-13T09:00:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    {
      id: 'm6-x4',
      threadId: '6',
      sender: 'staff',
      content: 'Great! For parking we have self-parking at $25/day and valet at $35/day, both available 24/7. The self-parking garage entrance is on Oak Street, right behind the hotel.',
      timestamp: new Date('2026-03-13T09:20:00'),
      channel: 'OTA',
      status: 'delivered',
    },
    // SMS: day-of check-in questions (Mar 16)
    {
      id: 'm13',
      threadId: '6',
      sender: 'guest',
      content: 'Hey, I\'m about an hour away. Just confirming — the self-parking garage is on Oak Street right?',
      timestamp: new Date('2026-03-16T14:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm14',
      threadId: '6',
      sender: 'ai',
      content: 'Yes! Self-parking garage entrance is on Oak Street, right behind the hotel. $25/day. Your room is 318 — check-in at the front desk whenever you arrive.',
      timestamp: new Date('2026-03-16T14:22:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm15',
      threadId: '6',
      sender: 'guest',
      content: 'Awesome! That really clears things up.',
      timestamp: new Date('2026-03-16T14:25:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== OLIVIA (thread 7) — Simple SMS =====
  '7': [
    {
      id: 'm16',
      threadId: '7',
      sender: 'guest',
      content: 'What time is breakfast served?',
      timestamp: new Date('2026-03-15T07:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm17',
      threadId: '7',
      sender: 'ai',
      content: 'Our complimentary breakfast buffet is served daily from 6:30 AM to 10:30 AM in the Garden Room on the 2nd floor.',
      timestamp: new Date('2026-03-15T07:02:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm18',
      threadId: '7',
      sender: 'guest',
      content: 'Fantastic! This is exactly what I needed.',
      timestamp: new Date('2026-03-15T07:05:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== NOAH (thread 8) — Simple SMS =====
  '8': [
    {
      id: 'm19',
      threadId: '8',
      sender: 'guest',
      content: 'Do you have any recommendations for local attractions? We have kids.',
      timestamp: new Date('2026-03-14T08:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm20',
      threadId: '8',
      sender: 'ai',
      content: 'Absolutely! For families: the Sciencenter is great for kids (10 min drive), Ithaca Falls is a quick walk, and the Farmer\'s Market is on Saturdays. We also have a pool and game room here at the hotel.',
      timestamp: new Date('2026-03-14T08:47:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm21',
      threadId: '8',
      sender: 'guest',
      content: 'Perfect! This information is incredibly useful.',
      timestamp: new Date('2026-03-14T08:50:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== EMMA (thread 9) — Simple SMS =====
  '9': [
    {
      id: 'm22',
      threadId: '9',
      sender: 'guest',
      content: 'Can I request a late checkout tomorrow?',
      timestamp: new Date('2026-03-16T08:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm23',
      threadId: '9',
      sender: 'ai',
      content: 'I\'d be happy to help! We can offer a late checkout until 1 PM tomorrow at no extra charge, or until 3 PM for $50. Which would you prefer?',
      timestamp: new Date('2026-03-16T08:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm24',
      threadId: '9',
      sender: 'guest',
      content: '1pm is perfect, thank you!',
      timestamp: new Date('2026-03-16T08:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== PRIYA (thread 17) — Simple SMS =====
  '17': [
    {
      id: 'm62',
      threadId: '17',
      sender: 'guest',
      content: 'Hi, could you arrange a taxi to the airport for tomorrow at 6 AM? Terminal 2.',
      timestamp: new Date('2026-03-16T09:15:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm62-r',
      threadId: '17',
      sender: 'staff',
      content: 'Of course! I\'ve booked a car for 6:00 AM pickup at the main entrance, destination airport Terminal 2. The driver will text you when they arrive. Safe travels!',
      timestamp: new Date('2026-03-16T09:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== YUKI (thread 18) — Simple SMS =====
  '18': [
    {
      id: 'm63',
      threadId: '18',
      sender: 'guest',
      content: 'Is there a Japanese restaurant nearby you would recommend?',
      timestamp: new Date('2026-03-16T08:50:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm63-r',
      threadId: '18',
      sender: 'ai',
      content: 'Yes! Miyake is excellent — authentic Japanese cuisine about a 10-minute walk from the hotel on Aurora Street. For sushi specifically, Ithaca Sushi is also nearby. Would you like me to make a reservation?',
      timestamp: new Date('2026-03-16T08:52:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== FATIMA AL-HASSAN (thread 19) — Diamond Elite VIP, TWO stays, full multi-channel =====
  '19': [
    // ---- FIRST STAY: Mar 7-14 ----
    // Email: welcome back (Mar 7)
    {
      id: 'm19-e1',
      threadId: '19',
      sender: 'staff',
      content: 'Dear Ms. Al-Hassan,\n\nWelcome back to The Grand Ithaca Hotel! We are delighted to host you again.\n\nAs a Diamond Elite member, you have been upgraded to our Executive Suite (room 602). Your preferred amenities (extra pillows, sparkling water, and fresh orchids) have been arranged.\n\nYour stay details:\n• Check-in: March 7, 2026\n• Check-out: March 14, 2026\n• Room: Executive Suite 602\n\nPlease don\'t hesitate to reach out if there is anything else we can prepare.\n\nWith warm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-07T08:00:00'),
      channel: 'Email',
      emailThreadId: 'email-19-welcome',
      isGuestJourney: true,
      status: 'delivered',
    },
    // SMS: room upgrade acknowledgment (Mar 7)
    {
      id: 'm19-s1',
      threadId: '19',
      sender: 'guest',
      content: 'Just checked in. The suite is gorgeous, thank you for the upgrade!',
      timestamp: new Date('2026-03-07T15:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm19-s2',
      threadId: '19',
      sender: 'staff',
      content: 'So glad you like it, Ms. Al-Hassan! We remembered you enjoy the view from the 6th floor. Let us know if you need anything at all.',
      timestamp: new Date('2026-03-07T15:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // WhatsApp: pool question (Mar 10)
    {
      id: 'm19-w1',
      threadId: '19',
      sender: 'guest',
      content: 'Is the pool heated? Thinking of a swim before my morning meetings 🏊‍♀️',
      timestamp: new Date('2026-03-10T06:30:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm19-w2',
      threadId: '19',
      sender: 'ai',
      content: 'Yes! The pool is heated to 82°F year-round and opens at 6 AM. Towels are provided poolside. Enjoy your swim!',
      timestamp: new Date('2026-03-10T06:32:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    // Email: checkout follow-up, thank you (Mar 14)
    {
      id: 'm19-e2',
      threadId: '19',
      sender: 'staff',
      content: 'Dear Ms. Al-Hassan,\n\nThank you for staying with us this past week. We hope you enjoyed your time at The Grand Ithaca.\n\nYour folio has been emailed separately. As a Diamond Elite member, your loyalty points for this stay (4,200 pts) will be credited within 48 hours.\n\nWe understand you\'ll be returning tomorrow for another stay — we\'re already preparing your suite!\n\nWarm regards,\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-14T11:00:00'),
      channel: 'Email',
      emailThreadId: 'email-19-checkout',
      isGuestJourney: true,
      status: 'delivered',
    },
    // ---- BETWEEN STAYS: Mar 14-15 ----
    // Email: welcome back again, car service arrangement
    {
      id: 'm19-e3',
      threadId: '19',
      sender: 'guest',
      content: 'Thank you for the wonderful first week! Looking forward to coming back tomorrow.\n\nCould you arrange a car service from the airport again? My flight arrives at 10:45 AM on the 15th (Emirates EK 203).\n\nAlso, would it be possible to get the Presidential Suite this time? I\'ll be hosting a small dinner on Sunday evening.\n\nBest,\nFatima',
      timestamp: new Date('2026-03-14T14:00:00'),
      channel: 'Email',
      emailThreadId: 'email-19-between',
      status: 'delivered',
    },
    {
      id: 'm19-e4',
      threadId: '19',
      sender: 'staff',
      content: 'Dear Ms. Al-Hassan,\n\nAbsolutely! Here\'s what we\'ve arranged for your return:\n\n• Car service: Black car at arrivals for Emirates EK 203 (10:45 AM, March 15). Driver will have a sign.\n• Room: Presidential Suite confirmed for March 15-20\n• Same amenities as before (extra pillows, sparkling water, orchids)\n\nFor your Sunday dinner, the Presidential Suite has a dining area that seats 8. Shall I arrange catering from our kitchen, or would you prefer a restaurant reservation?\n\nSafe travels!\n\nTheresa Webb\nGuest Services',
      timestamp: new Date('2026-03-14T15:30:00'),
      channel: 'Email',
      emailThreadId: 'email-19-between',
      status: 'delivered',
    },
    // ---- SECOND STAY: Mar 15-20 ----
    // SMS: suite upgrade reaction (Mar 15)
    {
      id: 'm64',
      threadId: '19',
      sender: 'guest',
      content: 'I just arrived and the Presidential Suite is incredible! Even better than the Executive. Thank you!',
      timestamp: new Date('2026-03-15T12:40:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm65',
      threadId: '19',
      sender: 'staff',
      content: 'Welcome back, Ms. Al-Hassan! We\'re so pleased you love it. The views from the Presidential are our best in the house. Let me know if I can help with anything for your Sunday dinner.',
      timestamp: new Date('2026-03-15T12:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // Email: dinner reservation at Il Ristorante Alga (Mar 16)
    {
      id: 'm19-e5',
      threadId: '19',
      sender: 'guest',
      content: 'Hi,\n\nI\'ve decided to do the dinner at Il Ristorante Alga instead of in-suite. Could you reserve for March 17th at 7:30 PM, party of 4?\n\nOne guest has a severe nut allergy — please let the kitchen know.\n\nThank you,\nFatima Al-Hassan',
      timestamp: new Date('2026-03-16T11:00:00'),
      channel: 'Email',
      emailThreadId: 'email-19-dinner',
      status: 'delivered',
    },
    {
      id: 'm19-e6',
      threadId: '19',
      sender: 'staff',
      content: 'Hi Fatima,\n\nYour reservation at Il Ristorante Alga is confirmed:\n\n• Date: March 17, 2026\n• Time: 7:30 PM\n• Party size: 4\n• Note: Severe nut allergy communicated to the kitchen\n\nThey have reserved the corner table by the window for your party. It\'s a 5-minute walk from the hotel, or I can arrange a car.\n\nEnjoy!\n\nBest,\nTheresa Webb',
      timestamp: new Date('2026-03-16T11:45:00'),
      channel: 'Email',
      emailThreadId: 'email-19-dinner',
      status: 'delivered',
    },
    // WhatsApp: quick pool question again (Mar 16)
    {
      id: 'm19-w3',
      threadId: '19',
      sender: 'guest',
      content: 'What time does the pool close tonight? Want to get a late swim in after dinner',
      timestamp: new Date('2026-03-16T15:30:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm19-w4',
      threadId: '19',
      sender: 'ai',
      content: 'The pool is open until 10 PM tonight. Heated to 82°F as always! Towels are provided poolside.',
      timestamp: new Date('2026-03-16T15:32:00'),
      channel: 'WhatsApp',
      status: 'delivered',
    },
    {
      id: 'm66',
      threadId: '19',
      sender: 'guest',
      content: 'Thank you for the upgrade, the suite is beautiful!',
      timestamp: new Date('2026-03-16T16:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== LUCIA (thread 20) — Simple SMS =====
  '20': [
    {
      id: 'm67',
      threadId: '20',
      sender: 'guest',
      content: 'Can someone bring extra blankets to room 226? It\'s pretty cold in here.',
      timestamp: new Date('2026-03-16T07:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm67-r',
      threadId: '20',
      sender: 'ai',
      content: 'Of course! I\'ll have housekeeping bring extra blankets to room 226 right away. Would you also like us to check the thermostat?',
      timestamp: new Date('2026-03-16T07:32:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== HIROSHI (thread 21) — Simple SMS =====
  '21': [
    {
      id: 'm68',
      threadId: '21',
      sender: 'guest',
      content: 'The room service menu — is it available after midnight?',
      timestamp: new Date('2026-03-15T23:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm69',
      threadId: '21',
      sender: 'ai',
      content: 'Yes! Our room service is available 24 hours. The full menu is in your room, or I can send you a digital copy. After midnight we have a slightly limited late-night menu.',
      timestamp: new Date('2026-03-15T23:46:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== INGRID (thread 22) — Simple SMS =====
  '22': [
    {
      id: 'm70',
      threadId: '22',
      sender: 'guest',
      content: 'Hi, I left my key card in the old room after I switched. Can I get a new one?',
      timestamp: new Date('2026-03-15T16:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm71',
      threadId: '22',
      sender: 'staff',
      content: 'Of course! I\'ve reissued a mobile key for your new room 608. You can also pick up a physical key at the front desk anytime.',
      timestamp: new Date('2026-03-15T16:05:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm72',
      threadId: '22',
      sender: 'guest',
      content: 'Perfect, I will pick up the key at the front desk.',
      timestamp: new Date('2026-03-15T16:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== THOMAS (thread 23) — Simple SMS =====
  '23': [
    {
      id: 'm73',
      threadId: '23',
      sender: 'guest',
      content: 'Do you have a business center or somewhere I can print documents?',
      timestamp: new Date('2026-03-16T08:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm73-r',
      threadId: '23',
      sender: 'ai',
      content: 'Yes! Our business center is on the lobby level, open 24/7. It has printers, scanners, and two workstations. Your room key gives you access.',
      timestamp: new Date('2026-03-16T08:02:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== RACHEL (thread 24) — Simple SMS =====
  '24': [
    {
      id: 'm74',
      threadId: '24',
      sender: 'guest',
      content: 'What are the hours for the rooftop bar?',
      timestamp: new Date('2026-03-15T15:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm75',
      threadId: '24',
      sender: 'ai',
      content: 'The rooftop bar is open daily from 4:00 PM to midnight. Happy hour is 4-6 PM with half-price cocktails!',
      timestamp: new Date('2026-03-15T15:02:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm76',
      threadId: '24',
      sender: 'guest',
      content: 'Thank you, that was very helpful!',
      timestamp: new Date('2026-03-15T15:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== CHLOE (thread 25) — Simple SMS =====
  '25': [
    {
      id: 'm77',
      threadId: '25',
      sender: 'guest',
      content: 'Is the spa open on Sundays?',
      timestamp: new Date('2026-03-16T09:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm77-r',
      threadId: '25',
      sender: 'ai',
      content: 'Yes! The Serenity Spa is open Sunday 9 AM to 6 PM. Would you like me to book a treatment?',
      timestamp: new Date('2026-03-16T09:02:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== ANDRE (thread 26) — Simple SMS =====
  '26': [
    {
      id: 'm78',
      threadId: '26',
      sender: 'guest',
      content: 'The air conditioning in room 124 seems to be blowing warm air.',
      timestamp: new Date('2026-03-15T21:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm79',
      threadId: '26',
      sender: 'staff',
      content: 'Sorry about that! I\'m sending maintenance to check the AC unit right away. Should be there within 10 minutes.',
      timestamp: new Date('2026-03-15T21:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm80',
      threadId: '26',
      sender: 'guest',
      content: 'All good now, the AC is working fine.',
      timestamp: new Date('2026-03-15T22:10:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== MAYA (thread 27) — Simple SMS =====
  '27': [
    {
      id: 'm81',
      threadId: '27',
      sender: 'guest',
      content: 'We loved the complimentary breakfast. The pastries were amazing. Thank you!',
      timestamp: new Date('2026-03-16T10:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm81-r',
      threadId: '27',
      sender: 'staff',
      content: 'That makes our day! I\'ll pass your kind words to Chef Marco. Glad you\'re enjoying your stay!',
      timestamp: new Date('2026-03-16T10:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    // Email: GJ checkout receipt, outbound-only (Email tab's Sent view)
    {
      id: 'm27-e1',
      threadId: '27',
      sender: 'staff',
      content: 'Dear Ms. Patel,\n\nThank you for staying with us. Your receipt is below:\n\n• Room 331, 3 nights — $567.00\n• Breakfast package — included\n• Taxes & fees — $79.38\n• Total charged — $646.38\n\nWe hope to welcome you back soon!\n\nThe Grand Ithaca Hotel',
      timestamp: new Date('2026-03-16T11:00:00'),
      channel: 'Email',
      emailThreadId: 'email-27-receipt',
      isGuestJourney: true,
      status: 'delivered',
    },
  ],

  // ===== SARAH MARTINEZ (thread 10) — Archived =====
  '10': [
    {
      id: 'm25',
      threadId: '10',
      sender: 'guest',
      content: 'Hi! Just checked in. The room looks lovely!',
      timestamp: new Date('2026-03-09T15:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm26',
      threadId: '10',
      sender: 'staff',
      content: 'Welcome Sarah! So glad you like it. Please let us know if you need anything during your stay.',
      timestamp: new Date('2026-03-09T15:22:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm27',
      threadId: '10',
      sender: 'guest',
      content: 'Thank you so much for the wonderful stay! Everything was perfect.',
      timestamp: new Date('2026-03-12T11:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== JAMES CHEN (thread 11) — Archived =====
  '11': [
    {
      id: 'm35',
      threadId: '11',
      sender: 'guest',
      content: "The WiFi in my room isn't working. I need to join a video call in 30 minutes.",
      timestamp: new Date('2026-03-10T14:15:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm36',
      threadId: '11',
      sender: 'staff',
      content: "I'm so sorry about that! Let me get our IT team to your room right away. In the meantime, the lobby has a separate network that's running fine.",
      timestamp: new Date('2026-03-10T14:16:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm42',
      threadId: '11',
      sender: 'guest',
      content: 'All set, thanks for resolving the WiFi issue.',
      timestamp: new Date('2026-03-11T16:45:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== MARIA GARCIA (thread 12) — Archived =====
  '12': [
    {
      id: 'm43',
      threadId: '12',
      sender: 'guest',
      content: "Hola! Is it possible to have a late checkout? My flight isn't until 6pm.",
      timestamp: new Date('2026-03-09T09:30:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm44',
      threadId: '12',
      sender: 'ai',
      content: 'Hi Maria! Yes, we can arrange a late checkout for you. Would 2:00 PM work for your schedule?',
      timestamp: new Date('2026-03-09T09:35:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm50',
      threadId: '12',
      sender: 'guest',
      content: 'Perfect, the late checkout worked out great. See you next time!',
      timestamp: new Date('2026-03-10T14:20:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== ROBERT THOMPSON (thread 13) — Archived =====
  '13': [
    {
      id: 'm51',
      threadId: '13',
      sender: 'guest',
      content: "I'd like to request a room upgrade if possible. Staying for 4 nights.",
      timestamp: new Date('2026-03-05T16:00:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm52',
      threadId: '13',
      sender: 'staff',
      content: "Good evening Mr. Thompson! As a Diamond Elite member, we'd be happy to upgrade you to a junior suite at no additional charge.",
      timestamp: new Date('2026-03-05T16:05:00'),
      channel: 'SMS',
      status: 'delivered',
    },
    {
      id: 'm61',
      threadId: '13',
      sender: 'guest',
      content: 'Appreciate all your help with the room upgrade and restaurant reservations!',
      timestamp: new Date('2026-03-09T10:15:00'),
      channel: 'SMS',
      status: 'delivered',
    },
  ],

  // ===== UNLINKED EMAIL THREADS (Email tab only — no messaging thread) =====
  // Keyed by emailThreadId. 'guest' sender = the external party.
  'email-u-wedding': [
    {
      id: 'mew-1',
      threadId: 'email-u-wedding',
      sender: 'guest',
      content: 'Hello,\n\nMy fiancé and I are planning our wedding for October 17–19, 2026 and are looking at Ithaca venues. Could you tell me about room block options for roughly 30 guests, and whether you have a space for a welcome reception on the Friday evening?\n\nThank you!\nSophia Reyes',
      timestamp: new Date('2026-03-15T09:20:00'),
      channel: 'Email',
      emailThreadId: 'email-u-wedding',
      cc: 'daniel.alvarez@gmail.com',
      status: 'delivered',
    },
    {
      id: 'mew-2',
      threadId: 'email-u-wedding',
      sender: 'staff',
      content: 'Hi Sophia,\n\nCongratulations! We\'d love to host your group. For 30 guests we offer a courtesy room block (10+ rooms) with a group rate, and our Garden Room is available for welcome receptions of up to 50.\n\nWould you like to schedule a call this week to walk through dates and pricing?\n\nBest,\nTheresa Webb\nGuest Services',
      timestamp: new Date('2026-03-15T14:05:00'),
      channel: 'Email',
      emailThreadId: 'email-u-wedding',
      status: 'delivered',
    },
    {
      id: 'mew-3',
      threadId: 'email-u-wedding',
      sender: 'guest',
      content: 'That sounds wonderful! Thursday afternoon works best for us — anytime after 2 PM. Also, is the Garden Room wheelchair accessible? My grandmother will be joining.\n\nSophia',
      timestamp: new Date('2026-03-17T08:45:00'),
      channel: 'Email',
      emailThreadId: 'email-u-wedding',
      cc: 'daniel.alvarez@gmail.com',
      status: 'delivered',
    },
  ],
  'email-u-vendor': [
    {
      id: 'mev-1',
      threadId: 'email-u-vendor',
      sender: 'guest',
      content: 'Hello,\n\nPlease find attached Invoice #8841 for May linen service, totaling $2,340.00. Payment is due within 30 days.\n\nNote: our rates will increase 4% starting July 1. Updated rate sheet to follow.\n\nRegards,\nCrisp Linen Co. Billing',
      timestamp: new Date('2026-03-16T07:30:00'),
      channel: 'Email',
      emailThreadId: 'email-u-vendor',
      status: 'delivered',
    },
  ],
  'email-u-promo': [
    {
      id: 'mep-1',
      threadId: 'email-u-promo',
      sender: 'guest',
      content: '🔥 48 HOURS ONLY — Refresh your lobby for less!\n\nUp to 40% off commercial seating, planters, and accent lighting. Trusted by 2,000+ hotels.\n\nShop the sale → hotelsupplypro.com/flash\n\nUnsubscribe | Manage preferences',
      timestamp: new Date('2026-03-13T06:15:00'),
      channel: 'Email',
      emailThreadId: 'email-u-promo',
      status: 'delivered',
    },
  ],
};

export const mockEmailThreads: EmailThread[] = [
  // Unlinked external senders (no reservation / messaging thread)
  {
    id: 'email-u-wedding',
    subject: 'Wedding Room Block Inquiry — October 2026',
    senderEmail: 'sophia.reyes@gmail.com',
    senderName: 'Sophia Reyes',
  },
  {
    id: 'email-u-vendor',
    subject: 'Invoice #8841 — May Linen Service',
    senderEmail: 'billing@crisplinenco.com',
    senderName: 'Crisp Linen Co.',
  },
  {
    id: 'email-u-promo',
    subject: '48-Hour Flash Sale — Lobby Furniture Refresh',
    senderEmail: 'deals@hotelsupplypro.com',
    senderName: 'HotelSupply Pro',
  },
  // GJ-only outbound (linked — GJ only sends to acknowledged reservations)
  {
    id: 'email-3-upsell',
    subject: 'Upgrade Your Stay — Spa & Late Checkout Offers',
    parentThreadId: '3',
  },
  {
    id: 'email-27-receipt',
    subject: 'Your Receipt — The Grand Ithaca Hotel',
    parentThreadId: '27',
  },
  {
    id: 'email-14-roomblock',
    subject: 'Group Room Block Confirmation — Smith Party (4 Rooms)',
    parentThreadId: '14',
  },
  {
    id: 'email-14-billing',
    subject: 'Direct Billing Setup — Meridian Consulting',
    parentThreadId: '14',
  },
  {
    id: 'email-14-meeting',
    subject: 'Meeting Room — Saturday Morning Review Session',
    parentThreadId: '14',
  },
  {
    id: 'email-1-confirm',
    subject: 'Reservation Confirmation #GIH-2026-4821',
    parentThreadId: '1',
  },
  {
    id: 'email-15-confirm',
    subject: 'Reservation Confirmation — Gold Elite Stay',
    parentThreadId: '15',
  },
  {
    id: 'email-2-welcome',
    subject: 'Welcome to The Grand Ithaca — Weekly Events',
    parentThreadId: '2',
  },
  {
    id: 'email-19-welcome',
    subject: 'Welcome Back, Ms. Al-Hassan — Diamond Elite',
    parentThreadId: '19',
  },
  {
    id: 'email-19-between',
    subject: 'Re: Returning March 15 — Car Service & Suite Request',
    parentThreadId: '19',
  },
  {
    id: 'email-19-dinner',
    subject: 'Dinner Reservation — Il Ristorante Alga, March 17',
    parentThreadId: '19',
  },
  {
    id: 'email-19-checkout',
    subject: 'Thank You for Staying With Us — See You Tomorrow!',
    parentThreadId: '19',
  },
];

export function getEmailThreadsForThread(threadId: string): EmailThread[] {
  return mockEmailThreads.filter((et) => et.parentThreadId === threadId);
}

export function getChannelsForThread(threadId: string): Set<import('./types').MessageChannel> {
  const messages = mockMessages[threadId] || [];
  const channels = new Set<import('./types').MessageChannel>();
  for (const msg of messages) {
    if (msg.channel) channels.add(msg.channel);
  }
  return channels;
}
